#import "EditorBackend.h"
#import "EditorModel.h"
#import <Security/Security.h>
#import <CommonCrypto/CommonDigest.h>
#include <math.h>
static NSString *const ConfigKey=@"TurboIO.DashboardBackend.Config.v1";
static NSDictionary *KeyQuery(void){return @{(__bridge id)kSecClass:(__bridge id)kSecClassGenericPassword,(__bridge id)kSecAttrService:@"TurboIO.DashboardBackend.v1",(__bridge id)kSecAttrAccount:@"active"};}
static BOOL Match(id s,NSString *pattern){return [s isKindOfClass:NSString.class]&&[s rangeOfString:pattern options:NSRegularExpressionSearch].location!=NSNotFound;}
NSString *TCEBackendOrigin(NSString *input){if(![input isKindOfClass:NSString.class]||input.length>512)return nil;NSURLComponents *u=[NSURLComponents componentsWithString:input];if(![u.scheme.lowercaseString isEqual:@"https"]||!u.host.length||u.user||u.password||u.query||u.fragment||(![u.path isEqual:@""]&&![u.path isEqual:@"/"])||(u.port&&(u.port.integerValue<1||u.port.integerValue>65535)))return nil;u.path=@"";return u.URL.absoluteString;}
NSString *TCEBackendDigest(NSDictionary *doc){if(!TCEValidateDraft(doc,nil))return nil;NSData *raw=[NSJSONSerialization dataWithJSONObject:doc options:NSJSONWritingSortedKeys|NSJSONWritingWithoutEscapingSlashes error:nil];if(!raw||raw.length>6000)return nil;unsigned char hash[CC_SHA256_DIGEST_LENGTH];CC_SHA256(raw.bytes,(CC_LONG)raw.length,hash);NSMutableString *s=[NSMutableString new];for(unsigned i=0;i<sizeof hash;i++)[s appendFormat:@"%02x",hash[i]];return s;}
BOOL TCEBackendValidJob(id j,NSString *device){if(![j isKindOfClass:NSDictionary.class]||!Match(j[@"id"],@"^[a-f0-9]{32}$")||!Match(j[@"hash"],@"^[a-f0-9]{64}$")||![j[@"device"]isEqual:device]||![j[@"state"]isEqual:@"awaiting_phone_approval"])return NO;NSNumber *r=j[@"revision"],*e=j[@"expires"];if(![r isKindOfClass:NSNumber.class]||CFGetTypeID((__bridge CFTypeRef)r)==CFBooleanGetTypeID()||!isfinite(r.doubleValue)||r.doubleValue<1||r.doubleValue>2147483647||floor(r.doubleValue)!=r.doubleValue||![e isKindOfClass:NSNumber.class]||CFGetTypeID((__bridge CFTypeRef)e)==CFBooleanGetTypeID()||!isfinite(e.doubleValue)||e.doubleValue<=NSDate.date.timeIntervalSince1970)return NO;id doc=j[@"document"];return TCEValidateDraft(doc,nil)&&[j[@"card"]isEqual:doc[@"id"]]&&[TCEBackendDigest(doc)isEqual:j[@"hash"]];}
NSDictionary *TCEBackendSettings(void){id d=[NSUserDefaults.standardUserDefaults objectForKey:ConfigKey];if(![d isKindOfClass:NSDictionary.class]||!TCEBackendOrigin(d[@"origin"])||![d[@"peer"]isKindOfClass:NSString.class]||![d[@"peer"]length]||[d[@"peer"]length]>256||!Match(d[@"backendDevice"],@"^[A-Za-z0-9_-]{1,64}$"))return @{};return @{ @"origin":d[@"origin"],@"peer":d[@"peer"],@"backendDevice":d[@"backendDevice"] };}
static NSString *Token(void){NSMutableDictionary *q=[KeyQuery()mutableCopy];q[(__bridge id)kSecReturnData]=@YES;q[(__bridge id)kSecMatchLimit]=(__bridge id)kSecMatchLimitOne;CFTypeRef out=NULL;if(SecItemCopyMatching((__bridge CFDictionaryRef)q,&out)!=errSecSuccess)return nil;NSData *data=CFBridgingRelease(out);return [[NSString alloc]initWithData:data encoding:NSUTF8StringEncoding];}
BOOL TCEBackendSave(NSString *origin,NSString *token,NSString *peer,NSString *device){origin=TCEBackendOrigin(origin);if(!origin||!Match(token,@"^[A-Za-z0-9_-]{32,128}$")||!peer.length||!Match(device,@"^[A-Za-z0-9_-]{1,64}$"))return NO;NSDictionary *attrs=@{(__bridge id)kSecValueData:[token dataUsingEncoding:NSUTF8StringEncoding],(__bridge id)kSecAttrAccessible:(__bridge id)kSecAttrAccessibleWhenUnlockedThisDeviceOnly};OSStatus status=SecItemUpdate((__bridge CFDictionaryRef)KeyQuery(),(__bridge CFDictionaryRef)attrs);if(status==errSecItemNotFound){NSMutableDictionary *q=[KeyQuery()mutableCopy];[q addEntriesFromDictionary:attrs];status=SecItemAdd((__bridge CFDictionaryRef)q,NULL);}if(status!=errSecSuccess)return NO;[NSUserDefaults.standardUserDefaults setObject:@{@"origin":origin,@"peer":peer,@"backendDevice":device} forKey:ConfigKey];return YES;}
void TCEBackendDisconnect(void){SecItemDelete((__bridge CFDictionaryRef)KeyQuery());[NSUserDefaults.standardUserDefaults removeObjectForKey:ConfigKey];}
@interface TCEBackendRequest()
@property NSURLSession *session;
@property NSMutableData *received;
@property(copy)void(^completion)(id,NSString *);
@property BOOL finished;
@end
@implementation TCEBackendRequest
+ (instancetype)request:(NSString *)path method:(NSString *)method body:(NSDictionary *)body completion:(void(^)(id,NSString *))done{return [self origin:TCEBackendSettings()[@"origin"] token:Token() configuration:nil path:path method:method body:body completion:done];}
+ (instancetype)origin:(NSString *)origin token:(NSString *)token configuration:(NSURLSessionConfiguration *)cfg path:(NSString *)path method:(NSString *)method body:(NSDictionary *)body completion:(void(^)(id,NSString *))done{
 TCEBackendRequest *r=[self new];r.completion=done;r.received=[NSMutableData new];origin=TCEBackendOrigin(origin);
 if(!origin||!Match(token,@"^[A-Za-z0-9_-]{32,128}$")||!Match(path,@"^/v1/(identity|jobs(/[a-f0-9]{32})?|phone/jobs/[a-f0-9]{32}/(approve|receipt))$")||![@[@"GET",@"POST"]containsObject:method]){[r finish:nil error:@"请配置 HTTPS 服务和本机专用 phone Token。"];return r;}
 NSMutableURLRequest *req=[NSMutableURLRequest requestWithURL:[NSURL URLWithString:[origin stringByAppendingString:path]]];req.HTTPMethod=method;[req setValue:[@"Bearer "stringByAppendingString:token] forHTTPHeaderField:@"Authorization"];[req setValue:@"application/json" forHTTPHeaderField:@"Accept"];if(body){if(![body isKindOfClass:NSDictionary.class]||![NSJSONSerialization isValidJSONObject:body]){[r finish:nil error:@"请求格式错误，未发送。"];return r;}req.HTTPBody=[NSJSONSerialization dataWithJSONObject:body options:0 error:nil];if(!req.HTTPBody||req.HTTPBody.length>8192){[r finish:nil error:@"请求超限，未发送。"];return r;}[req setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];}
 cfg=cfg?:NSURLSessionConfiguration.ephemeralSessionConfiguration;cfg.URLCache=nil;cfg.HTTPCookieStorage=nil;cfg.URLCredentialStorage=nil;cfg.requestCachePolicy=NSURLRequestReloadIgnoringLocalCacheData;cfg.timeoutIntervalForRequest=12;cfg.timeoutIntervalForResource=20;
 r.session=[NSURLSession sessionWithConfiguration:cfg delegate:r delegateQueue:NSOperationQueue.mainQueue];[[r.session dataTaskWithRequest:req]resume];return r;
}
- (void)finish:(id)value error:(NSString *)error{if(_finished)return;_finished=YES;void(^done)(id,NSString *)=_completion;_completion=nil;[_session invalidateAndCancel];_session=nil;if(done)dispatch_async(dispatch_get_main_queue(),^{done(value,error);});}
- (void)cancel{[self finish:nil error:@"请求取消；若刚提交批准，结果可能未知，请刷新状态。"];}
- (void)URLSession:(NSURLSession *)s task:(NSURLSessionTask *)t willPerformHTTPRedirection:(NSHTTPURLResponse *)response newRequest:(NSURLRequest *)request completionHandler:(void(^)(NSURLRequest *))completion{completion(nil);[self finish:nil error:@"服务重定向被拒绝，Token 未转发。"];}
- (void)URLSession:(NSURLSession *)s dataTask:(NSURLSessionDataTask *)task didReceiveResponse:(NSURLResponse *)response completionHandler:(void(^)(NSURLSessionResponseDisposition))completion{NSHTTPURLResponse *r=(id)response;if(![r isKindOfClass:NSHTTPURLResponse.class]||r.statusCode!=200||response.expectedContentLength>131072||![response.MIMEType isEqual:@"application/json"]){completion(NSURLSessionResponseCancel);[self finish:nil error:[NSString stringWithFormat:@"服务拒绝或返回格式错误（HTTP %ld），没有自动重试。",(long)([r isKindOfClass:NSHTTPURLResponse.class]?r.statusCode:0)]];return;}completion(NSURLSessionResponseAllow);}
- (void)URLSession:(NSURLSession *)s dataTask:(NSURLSessionDataTask *)t didReceiveData:(NSData *)data{if(_finished)return;if(data.length>131072-_received.length){[self finish:nil error:@"服务响应超限，已停止。"];return;}[_received appendData:data];}
- (void)URLSession:(NSURLSession *)s task:(NSURLSessionTask *)t didCompleteWithError:(NSError *)error{if(_finished)return;if(error){[self finish:nil error:@"网络请求未完成；没有自动重试，请刷新确认状态。"];return;}id value=[NSJSONSerialization JSONObjectWithData:_received options:0 error:nil];if(![value isKindOfClass:NSDictionary.class]&&![value isKindOfClass:NSArray.class]){[self finish:nil error:@"服务返回无效 JSON。"];return;}[self finish:value error:nil];}
@end
