#include "ride.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
uint32_t tn_crc(const uint8_t *p,size_t n){uint32_t c=~0u;while(n--){c^=*p++;for(unsigned i=0;i<8;i++)c=c&1?(c>>1)^0xedb88320:c>>1;}return ~c;}
int main(void){_Static_assert(sizeof(DRScene)==360,"wire scene");DRCommand c={.sid=10,.seq=1,.op=DR_SNAPSHOT,.scene={.phase=DR_QUOTE,.flags=DR_SHOW|DR_CONFIRM,.ttl=60,.nonce=123}},d;strcpy(c.scene.title,"快车报价");strcpy(c.scene.metric,"32元");uint8_t raw[DR_PACKET];assert(dr_encode(raw,sizeof raw,&c)==sizeof raw);assert(dr_decode(raw,sizeof raw,&d));DRState s={0};assert(dr_apply(&s,&d,100)==DR_OK);assert(!dr_confirm(&s,200));s.selected=true;assert(dr_confirm(&s,201));assert(!dr_confirm(&s,202));assert(dr_apply(&s,&d,203)==DR_OK&&s.consumed);c.seq++;assert(dr_encode(raw,sizeof raw,&c));assert(dr_decode(raw,sizeof raw,&d));assert(dr_apply(&s,&d,300)==DR_OK&&s.consumed&&s.received==100);memset(c.scene.title,0,sizeof c.scene.title);strcpy(c.scene.title,"changed");c.seq++;assert(dr_encode(raw,sizeof raw,&c));assert(dr_decode(raw,sizeof raw,&d));assert(dr_apply(&s,&d,400)==DR_BAD);c.scene.nonce++;assert(dr_encode(raw,sizeof raw,&c));assert(dr_decode(raw,sizeof raw,&d));assert(dr_apply(&s,&d,500)==DR_OK&&!s.consumed);s.selected=true;assert(!dr_confirm(&s,60500));dr_dismiss(&s);c.seq++;assert(dr_encode(raw,sizeof raw,&c));assert(dr_decode(raw,sizeof raw,&d));assert(dr_apply(&s,&d,700)==DR_OLD);
 for(unsigned i=0;i<DR_PACKET;i++){uint8_t saved=raw[i];raw[i]^=1;assert(!dr_decode(raw,sizeof raw,&d));raw[i]=saved;}
 uint32_t seed=7392;for(unsigned i=0;i<100000;i++){uint8_t fuzz[DR_PACKET];for(unsigned j=0;j<sizeof fuzz;j++){seed=seed*1664525+1013904223;fuzz[j]=seed>>24;}assert(!dr_decode(fuzz,sizeof fuzz,&d));}
 for(unsigned i=0;i<5000;i++){memset(&c,0,sizeof c);c.sid=11+i;c.seq=1;c.op=DR_SNAPSHOT;c.scene.ttl=15;c.scene.phase=DR_PICKUP;assert(dr_encode(raw,sizeof raw,&c));assert(dr_decode(raw,sizeof raw,&d));assert(dr_apply(&s,&d,0xfffffff0)==DR_OK);assert(!dr_expired(&s,30));assert(dr_expired(&s,15000));uint8_t reply[32];dr_reply(reply,&s,DR_OK,DR_ACK);assert(!memcmp(reply,"DRA1",4));}
 puts("PASS ride: strict sandbox wire, malformed CRC/UTF8, duplicate/old/dismissed/stale confirmation, time wrap, 100000 malformed + 5000 sessions");}
