import com.turboio.addon.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
public class CustomEnvelopeTest {
    static int checks;static void yes(boolean b){checks++;if(!b)throw new AssertionError("Envelope "+checks);}
    static byte[] envelope(String json){byte[] j=json.getBytes(StandardCharsets.UTF_8);ByteArrayOutputStream b=new ByteArrayOutputStream();b.write(8);b.write(1);b.write(16);b.write(6);b.write(26);int n=j.length;do{int v=n&127;n>>>=7;b.write(n==0?v:v|128);}while(n!=0);b.write(j,0,j.length);return b.toByteArray();}
    static byte[] append(byte[] a,byte... extra){byte[] out=Arrays.copyOf(a,a.length+extra.length);System.arraycopy(extra,0,out,a.length,extra.length);return out;}
    public static void main(String[] args){String j="{\"cmd\":\"turbo_nav_v1\",\"payload\":{\"data\":\"00ff\"}}";byte[] b=envelope(j);yes(Arrays.equals(CustomEnvelope.decode(b,"turbo_nav_v1",2),new byte[]{0,-1}));for(int n=0;n<b.length;n++)yes(CustomEnvelope.decode(Arrays.copyOf(b,n),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(append(b,(byte)34,(byte)0),"turbo_nav_v1",2)!=null);yes(CustomEnvelope.decode(append(b,(byte)32,(byte)0),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(append(b,(byte)34,(byte)1,(byte)0),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(append(b,(byte)8,(byte)1),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(append(b,(byte)56,(byte)1),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(append(b,(byte)40,(byte)0x80),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(append(b,(byte)40,(byte)255,(byte)255,(byte)255,(byte)255,(byte)16),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(b,"wrong",2)==null);yes(CustomEnvelope.decode(b,"turbo_nav_v1",3)==null);yes(CustomEnvelope.decode(b,"turbo_nav_v1",Integer.MAX_VALUE)==null);yes(CustomEnvelope.decode(new byte[1025],"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(envelope(j.replace("00ff","00FF")),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(envelope(j.replace("00ff","00fx")),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(envelope(j.replace("\"payload\":","\"cmd\":\"turbo_nav_v1\",\"payload\":")),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(envelope(j.replace("\"data\":","\"other\":1,\"data\":")),"turbo_nav_v1",2)==null);String nav=j.replace("\"data\":","\"value\":0,\"mode\":0,\"data\":");yes(CustomEnvelope.decode(envelope(nav),"turbo_nav_v1",2)!=null);yes(CustomEnvelope.decode(envelope(nav.replace("\"mode\":0","\"mode\":1")),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(envelope(nav.replace("\"value\":0","\"value\":\"0\"")),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(envelope(nav.replace("\"mode\":0,","")),"turbo_nav_v1",2)==null);yes(CustomEnvelope.decode(envelope(nav.replace("turbo_nav_v1","turbo_music_v1")),"turbo_music_v1",2)==null);System.out.println("CustomEnvelopeTest: "+checks+" assertions, truncation/duplicates/field types/length/hex checks");}
}
