package com.turboio.addon;
import java.util.*;import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.io.*;
public final class ReaderCaptionTest {
 static int checks;static void ok(boolean v){checks++;if(!v)throw new AssertionError("check "+checks);}interface Run{void go()throws Exception;}static void bad(Run r){try{r.go();throw new AssertionError("expected rejection");}catch(AssertionError e){throw e;}catch(Exception e){checks++;}}
 public static void main(String[]args)throws Exception{Path root=Paths.get(args[0]);Files.createDirectories(root);List<ReaderCodec.Book> books=new ArrayList<>();for(int i=0;i<7;i++){ReaderCodec.Book b=new ReaderCodec.Book(""+i,"原创测试书 "+i,"作者 Turbo",i+1);b.cover=new byte[5632];Arrays.fill(b.cover,(byte)(i*20));books.add(b);}byte[] shelf=ReaderCodec.shelf(books,0);ok(shelf.length==23360);ok(ReaderCodec.get(shelf,12)==4);byte[] last=ReaderCodec.shelf(books,4);ok(last.length==17536);bad(()->ReaderCodec.shelf(books,1));List<String> lines=ReaderCodec.wrap("测试正文\n"+String.join(" ",Collections.nCopies(200,"test"))+"\nEND");ok(lines.size()>10);byte[] page=ReaderCodec.window(books.get(0),lines,1,480,true);ok(ReaderCodec.get(page,16)==1);ok(ReaderCodec.get(page,24)==1);bad(()->ReaderCodec.window(books.get(0),lines,0,481,false));Files.write(root.resolve("shelf.bin"),shelf);Files.write(root.resolve("window.bin"),page);
  for(int op=1;op<=7;op++){byte[] body=op==2?new byte[8]:op==3?new byte[]{1,2,3}:op==5?new byte[8]:null;byte[] p=ReaderCodec.command(op,42,op,op==1?0:1,0,body);Files.write(root.resolve("op"+op+".bin"),p);ok(p.length<=512);ok(ReaderCodec.get(p,8)==42);byte[] copy=p.clone();Arrays.fill(copy,28,32,(byte)0);ok(ReaderCodec.get(p,28)==ReaderCodec.crc(copy));}bad(()->ReaderCodec.command(1,0,1,0,0,null));bad(()->ReaderCodec.command(3,1,1,1,0,new byte[481]));bad(()->ReaderCodec.utf8(new byte[]{(byte)0xff}));
  CaptionText parser=new CaptionText();CaptionText.Update a=parser.accept("conversation.item.input_audio_transcription.delta","a","1","hello",0);ok(a.channel.equals("source"));ok(parser.accept("conversation.item.input_audio_transcription.delta","a","1","again",0)==null);ok(parser.accept("response.text.delta","b","1","你好",0).text.equals("你好"));ok(parser.accept("conversation.item.input_audio_transcription.completed","c","1","hello world",0).text.equals("hello world"));ok(parser.accept("conversation.item.input_audio_transcription.delta","d","1","late",0)==null);bad(()->parser.accept("response.text.delta","e","1","bad",1));ok(parser.accept("response.audio.delta","x","1","AUDIO",0)==null);
  bad(()->BoundedWebSocket.frame(new ByteArrayInputStream(new byte[]{(byte)0x81,(byte)0x81,0})));ok(new String(BoundedWebSocket.frame(new ByteArrayInputStream(new byte[]{(byte)0x81,2,79,75})).bytes,StandardCharsets.UTF_8).equals("OK"));bad(()->BoundedWebSocket.frame(new ByteArrayInputStream(new byte[]{9,0})));bad(()->BoundedWebSocket.frame(new ByteArrayInputStream(new byte[]{(byte)0x82,0})));bad(()->BoundedWebSocket.frame(new ByteArrayInputStream(new byte[]{(byte)0x81,127,0,0,0,0,0,3,0,0})));
  System.out.println("Reader/caption/websocket checks: "+checks);}
}
