package com.turboio.addon;
import javax.net.ssl.*;import java.net.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import java.util.concurrent.*;
/** TLS-only RFC6455 client, masked output, bounded queue/messages, no redirects/extensions. */
final class BoundedWebSocket {
 interface Listener{void opened();void text(String s);void closed(String code);}
 private final Listener listener;private final ArrayBlockingQueue<byte[]> queue=new ArrayBlockingQueue<>(24);private volatile boolean ended;private volatile SSLSocket socket;private final SecureRandom random=new SecureRandom();private final Object writeLock=new Object();
 BoundedWebSocket(Listener l){listener=l;}
 void connect(String endpoint,String token){new Thread(()->{try{URI u=new URI(endpoint);if(!"wss".equals(u.getScheme())||u.getHost()==null||u.getUserInfo()!=null||u.getFragment()!=null||u.getPort()!=-1&&u.getPort()!=443||token.isEmpty()||token.length()>2048||token.contains("\r")||token.contains("\n"))throw new IOException();SSLSocket s=(SSLSocket)SSLSocketFactory.getDefault().createSocket();socket=s;if(ended){s.close();return;}s.connect(new InetSocketAddress(u.getHost(),443),12000);s.setSoTimeout(15000);SSLParameters p=s.getSSLParameters();p.setEndpointIdentificationAlgorithm("HTTPS");s.setSSLParameters(p);s.startHandshake();InputStream in=s.getInputStream();OutputStream out=s.getOutputStream();byte[] seed=new byte[16];random.nextBytes(seed);String key=Base64.getEncoder().encodeToString(seed);String path=u.getRawPath();if(path==null||path.isEmpty())path="/";if(u.getRawQuery()!=null)path+="?"+u.getRawQuery();String request="GET "+path+" HTTP/1.1\r\nHost: "+u.getHost()+"\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: "+key+"\r\nAuthorization: Bearer "+token+"\r\n\r\n";out.write(request.getBytes(StandardCharsets.US_ASCII));out.flush();ByteArrayOutputStream header=new ByteArrayOutputStream();int matched=0;byte[] end={13,10,13,10};while(matched<4){int v=in.read();if(v<0||header.size()>=16384)throw new IOException();header.write(v);matched=v==end[matched]?matched+1:v==13?1:0;}String[] hs=header.toString("US-ASCII").split("\r\n");if(!hs[0].matches("HTTP/1\\.[01] 101(?: .*)?"))throw new IOException();Map<String,String> fields=new HashMap<>();for(int i=1;i<hs.length;i++){int colon=hs[i].indexOf(':');if(colon>0)fields.put(hs[i].substring(0,colon).toLowerCase(Locale.ROOT),hs[i].substring(colon+1).trim());}String expected=Base64.getEncoder().encodeToString(MessageDigest.getInstance("SHA-1").digest((key+"258EAFA5-E914-47DA-95CA-C5AB0DC85B11").getBytes(StandardCharsets.US_ASCII)));if(!expected.equals(fields.get("sec-websocket-accept"))||!"websocket".equalsIgnoreCase(fields.get("upgrade"))||!Arrays.asList(fields.getOrDefault("connection","").toLowerCase(Locale.ROOT).split("\\s*,\\s*")).contains("upgrade")||fields.containsKey("sec-websocket-extensions"))throw new IOException();s.setSoTimeout(45000);
    Thread writer=new Thread(()->{try{while(!ended){byte[] b=queue.poll(1,TimeUnit.SECONDS);if(b!=null)write(out,1,b);}}catch(Exception e){finish("send_failed");}},"TurboIO-ws-send");writer.start();listener.opened();ByteArrayOutputStream fragments=null;while(!ended){Frame frame=frame(in);if(frame.op==8){finish("server_closed");return;}if(frame.op==9){write(out,10,frame.bytes);continue;}if(frame.op==10)continue;if(frame.op==1){if(fragments!=null)throw new IOException();if(frame.fin)listener.text(ReaderCodec.utf8(frame.bytes));else{fragments=new ByteArrayOutputStream();fragments.write(frame.bytes);}}else if(frame.op==0&&fragments!=null){if(fragments.size()+frame.bytes.length>131072)throw new IOException();fragments.write(frame.bytes);if(frame.fin){listener.text(ReaderCodec.utf8(fragments.toByteArray()));fragments=null;}}else throw new IOException();}
   }catch(Exception e){finish("transport_or_protocol_error");}},"TurboIO-ws-receive").start();}
 boolean send(String s){byte[] b=s.getBytes(StandardCharsets.UTF_8);if(ended||b.length>12000||!queue.offer(b)){finish("audio_backpressure");return false;}return true;}
 void write(OutputStream out,int op,byte[] b)throws IOException{synchronized(writeLock){if(ended)return;byte[] mask=new byte[4];random.nextBytes(mask);out.write(128|op);if(b.length<126)out.write(128|b.length);else{out.write(128|126);out.write(b.length>>>8);out.write(b.length);}out.write(mask);byte[] encoded=b.clone();for(int i=0;i<encoded.length;i++)encoded[i]^=mask[i%4];out.write(encoded);out.flush();}}
 static final class Frame{int op;boolean fin;byte[] bytes;}
 static Frame frame(InputStream in)throws IOException{int a=in.read(),b=in.read();if(a<0||b<0||(a&112)!=0||(b&128)!=0)throw new IOException("frame header");int op=a&15;boolean fin=(a&128)!=0;long n=b&127;if(n==126)n=(readByte(in)<<8)|readByte(in);else if(n==127){n=0;for(int i=0;i<8;i++){int v=readByte(in);if(i==0&&v!=0)throw new IOException();n=(n<<8)|v;if(n>131072)throw new IOException();}}if(n>131072||op>=8&&(!fin||n>125)||!Arrays.asList(0,1,8,9,10).contains(op))throw new IOException("frame bounds");Frame f=new Frame();f.op=op;f.fin=fin;f.bytes=new byte[(int)n];int pos=0;while(pos<n){int r=in.read(f.bytes,pos,(int)n-pos);if(r<0)throw new EOFException();pos+=r;}return f;}
 private static int readByte(InputStream in)throws IOException{int b=in.read();if(b<0)throw new EOFException();return b;}
 void close(){finish("closed");}
 private void finish(String reason){boolean report;synchronized(this){report=!ended;ended=true;}queue.clear();SSLSocket s=socket;if(s!=null)try{s.close();}catch(IOException ignored){}if(report)listener.closed(reason);}
}
