package com.turboio.addon;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import static com.turboio.addon.BoundedJson.*;

/** TCE1 native dashboard contract, platform independent. Icons supplied as mono1 bytes. */
public final class CardCodec {
    public interface Icons{byte[] pixels(int index,int size);}
    private static void need(boolean c){if(!c)throw new IllegalArgumentException("卡片字段、坐标或预算超限");}
    public static Map<String,Object> object(Object...pairs){Map<String,Object> m=new TreeMap<>();for(int i=0;i<pairs.length;i+=2)m.put((String)pairs[i],pairs[i+1]);return m;}
    public static byte[] encode(Map<String,Object> doc,Icons icons){keys(doc,"schema","id","name","components");number(doc.get("schema"),1,1);need(text(doc.get("id"),48).matches("turbo_ui_card_[a-z0-9_]+"));text(doc.get("name"),60);need(canonical(doc).length<=6000);List<Object> cs=list(doc.get("components"));need(cs.size()>0&&cs.size()<=12);Set<String> ids=new HashSet<>();int images=0,charts=0,pixels=0;ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] header={'T','C','E','1',(byte)cs.size(),0,0,0};out.write(header,0,8);
        for(Object o:cs){Map<String,Object> c=map(o);String id=text(c.get("id"),24);need(id.matches("[a-z0-9_]+")&&ids.add(id));int x=number(c.get("x"),6,248),y=number(c.get("y"),6,186),w=number(c.get("w"),2,244),h=number(c.get("h"),2,182);need((x|y|w|h)%2==0&&x+w<=250&&y+h<=188);String k=text(c.get("kind"),16);List<String> expected=new ArrayList<>(Arrays.asList("id","kind","x","y","w","h"));int type,a=0,b=0;byte[] body=new byte[0];
            if(k.equals("text")){type=1;expected.addAll(Arrays.asList("text","font","align"));a=number(c.get("font"),14,28);need(Arrays.asList(14,16,18,20,24,28).contains(a)&&h>=a+4&&w>=16);b=Arrays.asList("left","center","right").indexOf(c.get("align"));need(b>=0);body=text(c.get("text"),96).getBytes(StandardCharsets.UTF_8);}
            else if(k.equals("icon")||k.equals("image")){type=2;need(++images<=4&&w==h&&Arrays.asList(16,24,32,48).contains(w));pixels+=w*h;if(k.equals("icon")){expected.add("icon");int index=number(c.get("icon"),0,15);body=icons.pixels(index,w);}else{expected.addAll(Arrays.asList("format","pixels"));need("mono1-msb".equals(c.get("format")));String raw=text(c.get("pixels"),384);body=Base64.getDecoder().decode(raw);need(Base64.getEncoder().encodeToString(body).equals(raw));}need(body!=null&&body.length==w*h/8);}
            else if(k.equals("progress")){type=3;expected.add("value");a=number(c.get("value"),0,100);need(w>=16&&h<=12);}
            else if(k.equals("barChart")||k.equals("lineChart")){type=k.equals("barChart")?4:5;expected.add("points");List<Object> points=list(c.get("points"));need(++charts<=2&&w>=64&&h>=32&&points.size()>=2&&points.size()<=8);pixels+=((w+3)/4)*4*h;body=new byte[points.size()];for(int i=0;i<body.length;i++)body[i]=(byte)number(points.get(i),0,100);}
            else if(k.equals("divider")){type=6;need(h==2&&w>=8);}else{need(k.equals("frame")&&w>=16&&h>=16);type=7;}
            keys(c,expected.toArray(new String[0]));need(pixels<=32768);byte[] row={(byte)type,(byte)x,(byte)y,(byte)w,(byte)h,(byte)a,(byte)b,0,(byte)body.length,(byte)(body.length>>>8)};out.write(row,0,10);out.write(body,0,body.length);
        }byte[] bytes=out.toByteArray();need(bytes.length<=2048);bytes[6]=(byte)bytes.length;bytes[7]=(byte)(bytes.length>>>8);return bytes;
    }
    public static Map<String,Object> install(Map<String,Object> doc,Icons icons){String id=(String)doc.get("id"),name=(String)doc.get("name"),encoded="TCE1:"+Base64.getEncoder().encodeToString(encode(doc,icons));Map<String,Object> extra=object("widgetId",id,"name",name,"uiContent",object("createSurface",object("surfaceId",id,"catalogId","https://rayneo.com/a2ui/catalogs/glasses-base/v1/catalog.json"),"updateComponents",object("surfaceId",id,"components",Arrays.asList(object("id","root","component","Text","text",encoded,"variant","caption")))));return object("cmd","widget_install","payload",object("data",object("type","a2ui","id",id,"name",name,"extras",new String(canonical(extra),StandardCharsets.UTF_8))));}
    public static List<Object> rows(Map<String,Object> config){List<Object> rows=list(config.get("widgets_v2"));need(rows.size()<=32);Set<String> ids=new HashSet<>();for(Object o:rows){Map<String,Object> r=map(o);need(ids.add(text(r.get("id"),128)));text(r.get("type"),128);}return rows;}
    public static Map<String,Object> first(Map<String,Object> config,String id){List<Object> items=new ArrayList<>();Map<String,Object> own=null;for(Object o:rows(config)){Map<String,Object> r=map(o);if(id.equals(r.get("id")))own=r;else items.add(r);}need(own!=null&&"a2ui".equals(own.get("type")));items.add(0,own);Map<String,Object> changed=new TreeMap<>(config);changed.put("widgets_v2",items);return changed;}
    public static boolean preserves(Map<String,Object> before,Map<String,Object> after,String id){try{List<Object> x=new ArrayList<>(rows(before)),y=new ArrayList<>(rows(after));x.removeIf(o->id.equals(map(o).get("id")));y.removeIf(o->id.equals(map(o).get("id")));Map<String,Object>a=new TreeMap<>(before),b=new TreeMap<>(after);a.remove("widgets_v2");b.remove("widgets_v2");return a.equals(b)&&x.equals(y);}catch(RuntimeException e){return false;}}
    static Map<String,Object> component(String id,String kind,int x,int y,int w,int h,Object...extra){Map<String,Object> c=object("id",id,"kind",kind,"x",x,"y",y,"w",w,"h",h);c.putAll(object(extra));return c;}
    static Map<String,Object> txt(String id,String text,int x,int y,int w,int font){return component(id,"text",x,y,w,font+4,"text",text,"font",font,"align","left");}
    static final String[] NAMES={"资源与额度","双列指标","大数字","柱状图","趋势折线","文字便笺"};
    public static Map<String,Object> template(int index,String id){List<Object> c=new ArrayList<>();if(index==0){Collections.addAll(c,component("i1","icon",6,12,32,32,"icon",0),txt("t1","Codex Pro 20x",44,6,200,18),txt("v1","Weekly 99%",44,32,200,16),component("p1","progress",44,56,200,4,"value",99),component("i2","icon",6,76,32,32,"icon",1),txt("t2","Claude Max 20x",44,68,200,18),txt("v2","5h 90% / Week 85%",44,94,200,16),component("p2","progress",44,118,200,4,"value",85),component("i3","icon",6,148,32,32,"icon",2),txt("t3","MacBook Pro · M5 Max",44,132,200,14),txt("v3","RAM 37.5 / 128 GB",44,152,200,14),txt("v4","SSD 1.4 / 2 TB",44,170,200,14));}
        else if(index==1)Collections.addAll(c,txt("title","今日概览",10,8,232,20),txt("a","专注",10,48,104,16),txt("b","阅读",136,48,104,16),txt("av","75%",10,78,104,28),txt("bv","90%",136,78,104,28),component("ap","progress",10,126,104,8,"value",75),component("bp","progress",136,126,104,8,"value",90));
        else if(index==2)Collections.addAll(c,component("icon","icon",10,10,48,48,"icon",4),txt("title","内存余量",72,18,170,20),txt("value","37.5 GB",16,78,220,28),component("bar","progress",16,134,224,8,"value",29),txt("note","总量 128 GB · 演示",16,158,224,16));
        else if(index==3||index==4)Collections.addAll(c,txt("title",index==3?"本周专注":"额度趋势",10,8,232,20),component("chart",index==3?"barChart":"lineChart",10,42,232,104,"points",Arrays.asList(25,48,35,72,65,90,85)),txt("note","0–100 · 静态示例",10,162,232,16));
        else Collections.addAll(c,txt("title","给今天的一句话",12,12,228,20),component("rule","divider",12,44,228,2),txt("a","专注一件事",12,64,228,24),txt("b","让好想法慢慢发生",12,104,228,18),txt("c","Turbo IO",12,152,228,16));return object("schema",1,"id",id,"name",NAMES[index],"components",c);}
}
