package com.turboio.addon;
import android.app.*;
import android.content.*;
import android.graphics.*;
import android.text.InputType;
import android.widget.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import static com.turboio.addon.BoundedJson.*;

final class CardUI {
    private static final Set<Runnable> savedObservers=new HashSet<>();
    private static List<Object> drafts(Activity a){String s=a.getSharedPreferences("turboio_cards",0).getString("drafts","[]");if(s.getBytes(StandardCharsets.UTF_8).length>64000)throw new IllegalArgumentException("草稿库超出预算，原始数据保留");List<Object> list=list(read(s.getBytes(StandardCharsets.UTF_8)));if(list.size()>8)throw new IllegalArgumentException("草稿过多，原始数据保留");Set<String> ids=new HashSet<>();for(Object o:list){Map<String,Object> d=map(o);CardCodec.encode(d,CardIcons::pixels);if(!ids.add((String)d.get("id")))throw new IllegalArgumentException("草稿ID重复，原始数据保留");}return list;}
    private static void save(Activity a,Map<String,Object> doc){CardCodec.encode(doc,CardIcons::pixels);List<Object> items=drafts(a);int index=-1;for(int i=0;i<items.size();i++)if(map(items.get(i)).get("id").equals(doc.get("id")))index=i;if(index>=0)items.set(index,doc);else{if(items.size()>=8)throw new IllegalArgumentException("本机最多保存8张草稿");items.add(doc);}byte[] b=canonical(items);if(b.length>64000)throw new IllegalArgumentException();if(!a.getSharedPreferences("turboio_cards",0).edit().putString("drafts",new String(b,StandardCharsets.UTF_8)).commit())throw new IllegalStateException("storage");for(Runnable r:new ArrayList<>(savedObservers))r.run();}
    static void show(Activity a){EditorialUI.Screen s=new EditorialUI.Screen(a,"仪表盘");LinearLayout b=s.body;EditorialUI.button(a,b,"读取眼镜卡片 / 检查天气",false,()->inspect(a));EditorialUI.button(a,b,"新建卡片 · 模板预览",true,()->templates(a));EditorialUI.button(a,b,"AI 生成 · 使用自有模型",false,()->generate(a));EditorialUI.button(a,b,"导入卡片 JSON",false,()->DocumentPicker.pick(a,6000,bytes->{try{Map<String,Object> d=map(read(bytes));CardCodec.encode(d,CardIcons::pixels);editor(a,d);}catch(RuntimeException e){EditorialUI.notice(a,"卡片不符合TCE1契约，未保存或发送");}}));LinearLayout saved=EditorialUI.column(a);b.addView(saved);EditorialUI.button(a,b,"刷新本机草稿",false,()->library(a,saved));library(a,saved);Runnable refresh=()->library(a,saved);savedObservers.add(refresh);s.dialog.setOnDismissListener(d->savedObservers.remove(refresh));}
    private static void inspect(Activity a){EditorialUI.Screen s=new EditorialUI.Screen(a,"眼镜卡片状态");TextView status=EditorialUI.text(a,"",15,EditorialUI.INK);s.body.addView(status);EditorialUI.button(a,s.body,"重新读取（不修改）",false,CardTransport::inspect);s.body.addView(EditorialUI.text(a,"这是实际眼镜配置，不是手机草稿。天气卡片与天气数据是两件事；检查不会新增、删除或重排其他卡片。",13,EditorialUI.MUTED));android.os.Handler h=new android.os.Handler(android.os.Looper.getMainLooper());Runnable tick=new Runnable(){public void run(){if(!s.dialog.isShowing())return;status.setText(CardTransport.status()+"\n\n"+NativeTransfer.diagnostic());h.postDelayed(this,500);}};h.post(tick);s.dialog.setOnDismissListener(d->h.removeCallbacks(tick));CardTransport.inspect();}
    private static void library(Activity a,LinearLayout b){b.removeAllViews();try{for(Object o:drafts(a)){Map<String,Object> d=map(o);LinearLayout c=EditorialUI.card(a,b);c.addView(new CardCanvas(a,d,false));EditorialUI.button(a,c,(String)d.get("name"),false,()->editor(a,d));}if(b.getChildCount()==0)b.addView(EditorialUI.text(a,"从模板或一句描述开始。草稿保存在手机，发送前始终预览并确认。",14,EditorialUI.MUTED));}catch(RuntimeException e){b.addView(EditorialUI.text(a,"本机草稿库未通过校验，已保留原始数据并暂停写入，请先导出排查。",14,EditorialUI.MUTED));}}
    private static void templates(Activity a){EditorialUI.Screen s=new EditorialUI.Screen(a,"选择模板");for(int i=0;i<6;i++){Map<String,Object> d=CardCodec.template(i,"turbo_ui_card_"+UUID.randomUUID().toString().replace("-",""));LinearLayout c=EditorialUI.card(a,s.body);c.addView(new CardCanvas(a,d,false));EditorialUI.button(a,c,CardCodec.NAMES[i],false,()->editor(a,d));}}
    private static EditText field(Activity a,LinearLayout b,String label,String value){b.addView(EditorialUI.text(a,label,14,EditorialUI.MUTED));EditText e=new EditText(a);e.setText(value);e.setTextColor(EditorialUI.INK);e.setTextSize(16);e.setBackgroundTintList(android.content.res.ColorStateList.valueOf(EditorialUI.LIME));b.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
    private static void generate(Activity a){EditorialUI.Screen s=new EditorialUI.Screen(a,"AI 生成卡片");EditText input=field(a,s.body,"描述发送给你在模型设置中配置的服务","做一个三行资源额度卡片，数据标为示例");TextView status=EditorialUI.text(a,"生成后只预览，不会自动发送眼镜或接入你的后端。",14,EditorialUI.MUTED);s.body.addView(status);TextView button=EditorialUI.button(a,s.body,"生成布局",true,()->{});button.setOnClickListener(v->{button.setEnabled(false);status.setText("模型生成中 · 正在等待并校验JSON…");String prompt=input.getText().toString();new Thread(()->{try{Map<String,Object> d=CardAI.generate(a.getApplicationContext(),prompt);NativeTransfer.MAIN.post(()->{if(!s.dialog.isShowing())return;button.setEnabled(true);status.setText("本地约束校验通过，请预览");editor(a,d);});}catch(Exception e){NativeTransfer.MAIN.post(()->{if(s.dialog.isShowing()){button.setEnabled(true);status.setText("生成失败：请检查模型配置，或简化描述。无内容发送到眼镜。");}});}},"TurboIO-card-ai").start();});}
    private static void editor(Activity a,Map<String,Object> initial){new Editor(a,initial);}
    private static final class Editor {
        final Activity a;final EditorialUI.Screen screen;final CardCanvas canvas;final TextView status;final LinearLayout properties;final ArrayDeque<byte[]> undo=new ArrayDeque<>();Map<String,Object> doc;int selected=-1;boolean refreshing;
        Editor(Activity a,Map<String,Object> d){this.a=a;doc=map(read(canonical(d)));screen=new EditorialUI.Screen(a,(String)d.get("name"));canvas=new CardCanvas(a,doc,true);screen.body.addView(canvas);screen.body.addView(EditorialUI.text(a,"点选组件后拖动；位置吸附2像素网格。下方可修改文字、字号和数值。",13,EditorialUI.MUTED));properties=EditorialUI.card(a,screen.body);status=EditorialUI.text(a,CardTransport.status(),13,EditorialUI.MUTED);screen.body.addView(status);canvas.listen(new CardCanvas.Changed(){public void selected(int i){selected=i;properties();}public void moved(Map<String,Object> d){commit(d);}});EditorialUI.button(a,screen.body,"选择组件（列表）",false,()->{List<Object> cs=list(doc.get("components"));String[] names=new String[cs.size()];for(int i=0;i<names.length;i++){Map<String,Object> c=map(cs.get(i));names[i]=c.get("id")+" · "+c.get("kind");}new AlertDialog.Builder(a).setTitle("选择组件").setItems(names,(dialog,i)->canvas.select(i)).show();});EditorialUI.button(a,screen.body,"添加组件",false,this::add);EditorialUI.button(a,screen.body,"撤销上一步",false,()->{if(!undo.isEmpty()){doc=map(read(undo.removeLast()));canvas.set(doc);properties();}});EditorialUI.button(a,screen.body,"保存草稿",false,()->{try{save(a,doc);status.setText("草稿已保存到本机");}catch(RuntimeException e){status.setText("未保存：草稿可能超限或损坏，原始数据已保留");}});
            Switch first=new Switch(a);first.setText("发送后置顶，其他卡片顺延");first.setTextColor(EditorialUI.INK);screen.body.addView(first);EditorialUI.button(a,screen.body,"发送当前预览到眼镜",true,()->{Map<String,Object> snapshot=map(read(canonical(doc)));EditorialUI.confirm(a,"发送这张卡片？","需要TCE1或更新的兼容固件。请先结束固件升级和其他任务。仅发送当前预览数据，不代表真实账号额度。",()->CardTransport.publish(snapshot,first.isChecked()));});EditorialUI.button(a,screen.body,"分享配置 JSON",false,()->a.startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("application/json").putExtra(Intent.EXTRA_TEXT,new String(canonical(doc),StandardCharsets.UTF_8)),"分享卡片配置")));EditorialUI.button(a,screen.body,"从眼镜移除本卡",false,()->EditorialUI.confirm(a,"移除本卡？","保留手机草稿及其他眼镜卡片。",()->CardTransport.remove((String)doc.get("id"))));CardTransport.listen(()->status.setText(CardTransport.status()));screen.dialog.setOnDismissListener(x->CardTransport.detach());properties();}
        void commit(Map<String,Object> next){try{CardCodec.encode(next,CardIcons::pixels);undo.addLast(canonical(doc));while(undo.size()>20)undo.removeFirst();doc=map(read(canonical(next)));canvas.set(doc);status.setText("布局已修改，记得保存；尚未发送");properties();}catch(RuntimeException e){EditorialUI.notice(a,"超出尺寸、文字或内存预算，已保留原稿");canvas.set(doc);}}
        void replace(Map<String,Object> c){Map<String,Object> next=map(read(canonical(doc)));list(next.get("components")).set(selected,c);commit(next);}
        void properties(){properties.removeAllViews();if(selected<0||selected>=list(doc.get("components")).size()){properties.addView(EditorialUI.text(a,"先点选一个组件",16,EditorialUI.MUTED));return;}Map<String,Object> c=map(list(doc.get("components")).get(selected));String kind=(String)c.get("kind");properties.addView(EditorialUI.text(a,c.get("id")+" · "+kind,16,EditorialUI.LIME));if(kind.equals("text")){EditText input=field(a,properties,"文字",(String)c.get("text"));EditorialUI.button(a,properties,"应用文字",false,()->{Map<String,Object> next=new TreeMap<>(c);next.put("text",input.getText().toString());replace(next);});LinearLayout fonts=new LinearLayout(a);properties.addView(fonts);for(int size:new int[]{14,16,18,20,24,28}){TextView t=EditorialUI.text(a,""+size,14,EditorialUI.INK);t.setGravity(android.view.Gravity.CENTER);fonts.addView(t,new LinearLayout.LayoutParams(0,EditorialUI.dp(a,48),1));t.setOnClickListener(v->{Map<String,Object> next=new TreeMap<>(c);next.put("font",size);next.put("h",Math.max(size+4,((Number)c.get("h")).intValue()));replace(next);});}}
            if(kind.equals("progress")){SeekBar slider=new SeekBar(a);slider.setMax(100);slider.setProgress(((Number)c.get("value")).intValue());properties.addView(slider);slider.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int n,boolean user){}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){Map<String,Object> next=new TreeMap<>(c);next.put("value",b.getProgress());replace(next);}});}
            if(kind.equals("icon"))EditorialUI.button(a,properties,"更换图标",false,()->new AlertDialog.Builder(a).setItems(CardIcons.NAMES,(d,i)->{Map<String,Object> next=new TreeMap<>(c);next.put("icon",i);replace(next);}).show());
            if(kind.endsWith("Chart")){EditText points=field(a,properties,"2–8个0–100整数，逗号分隔",list(c.get("points")).toString().replace("[","").replace("]",""));EditorialUI.button(a,properties,"应用图表数值",false,()->{try{List<Object> ns=new ArrayList<>();for(String s:points.getText().toString().replace('，',',').split(","))ns.add(Integer.parseInt(s.trim()));Map<String,Object> next=new TreeMap<>(c);next.put("points",ns);replace(next);}catch(RuntimeException e){EditorialUI.notice(a,"请输入逗号分隔的整数");}});}
            EditorialUI.button(a,properties,"位置和尺寸",false,()->geometry(c));EditorialUI.button(a,properties,"删除此组件",false,()->{Map<String,Object> next=map(read(canonical(doc)));list(next.get("components")).remove(selected);selected=-1;canvas.selected=-1;commit(next);});}
        void geometry(Map<String,Object> c){LinearLayout b=EditorialUI.column(a);b.setPadding(30,15,30,15);b.setBackgroundColor(EditorialUI.BG);String[] keys={"x","y","w","h"};EditText[] fields=new EditText[4];for(int i=0;i<4;i++){fields[i]=field(a,b,keys[i],c.get(keys[i]).toString());fields[i].setInputType(InputType.TYPE_CLASS_NUMBER);}AlertDialog dialog=new AlertDialog.Builder(a).setTitle("偶数像素，边界内移动").setView(b).setNegativeButton("取消",null).setPositiveButton("应用",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{try{Map<String,Object> next=new TreeMap<>(c);for(int i=0;i<4;i++)next.put(keys[i],Integer.parseInt(fields[i].getText().toString()));Map<String,Object> proposed=map(read(canonical(doc)));list(proposed.get("components")).set(selected,next);CardCodec.encode(proposed,CardIcons::pixels);replace(next);dialog.dismiss();}catch(RuntimeException e){EditorialUI.notice(a,"请输入边界内的有效偶数尺寸");}}));dialog.show();}
        void add(){String[] names={"文字","图标","图片（居中裁剪）","进度条","柱状图","折线图","分隔线","边框"};new AlertDialog.Builder(a).setTitle("添加组件").setItems(names,(d,i)->{if(i==2){DocumentPicker.pick(a,8*1024*1024,this::image);return;}String id="c"+UUID.randomUUID().toString().substring(0,8);Map<String,Object> c;if(i==0)c=CardCodec.txt(id,"新文字",12,12,120,18);else if(i==1)c=CardCodec.component(id,"icon",12,12,32,32,"icon",0);else if(i==3)c=CardCodec.component(id,"progress",12,12,120,8,"value",50);else if(i==4||i==5)c=CardCodec.component(id,i==4?"barChart":"lineChart",12,12,120,64,"points",Arrays.asList(20,50,40,80));else if(i==6)c=CardCodec.component(id,"divider",12,12,120,2);else c=CardCodec.component(id,"frame",12,12,120,60);append(c);}).show();}
        void append(Map<String,Object> c){Map<String,Object> next=map(read(canonical(doc)));list(next.get("components")).add(c);commit(next);canvas.select(list(doc.get("components")).size()-1);}
        void image(byte[] bytes){try{BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,bounds);if(bounds.outWidth<=0||bounds.outHeight<=0)throw new IllegalArgumentException();BitmapFactory.Options opts=new BitmapFactory.Options();opts.inSampleSize=1;while(Math.max(bounds.outWidth,bounds.outHeight)/opts.inSampleSize>1024)opts.inSampleSize*=2;Bitmap src=BitmapFactory.decodeByteArray(bytes,0,bytes.length,opts);if(src==null)throw new IllegalArgumentException();int side=Math.min(src.getWidth(),src.getHeight());Bitmap tiny=Bitmap.createBitmap(32,32,Bitmap.Config.ARGB_8888);Canvas cv=new Canvas(tiny);cv.drawColor(Color.BLACK);cv.drawBitmap(src,new Rect((src.getWidth()-side)/2,(src.getHeight()-side)/2,(src.getWidth()+side)/2,(src.getHeight()+side)/2),new Rect(0,0,32,32),new Paint(Paint.FILTER_BITMAP_FLAG));src.recycle();int[] pixels=new int[1024];tiny.getPixels(pixels,0,32,0,0,32,32);tiny.recycle();byte[] mono=new byte[128];for(int i=0;i<pixels.length;i++){int v=pixels[i];if((Color.red(v)*299+Color.green(v)*587+Color.blue(v)*114)/1000>=90)mono[i/8]|=128>>>(i%8);}append(CardCodec.component("img"+UUID.randomUUID().toString().substring(0,8),"image",12,12,32,32,"format","mono1-msb","pixels",Base64.getEncoder().encodeToString(mono)));}catch(RuntimeException e){EditorialUI.notice(a,"无法读取此图片，请选择普通PNG/JPG（不超过8MiB）");}}
    }
}
