package com.turboio.addon;
import android.content.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.json.*;

/** Opt-in model generation; always validates locally and previews before publication. */
final class CardAI {
    static Map<String,Object> generate(Context context,String prompt)throws Exception{if(prompt==null||prompt.trim().isEmpty()||prompt.length()>4000)throw new IllegalArgumentException("描述需要1–4000字");SharedPreferences p=context.getSharedPreferences("turboio_settings",0);String endpoint=p.getString("endpoint","https://api.deepseek.com/chat/completions"),model=p.getString("model","deepseek-flash"),key=SecretStore.get(context);if(!ChatPolicy.endpoint(endpoint)||key.isEmpty())throw new IllegalArgumentException("请先在模型与对话中配置服务和Key");String schema;try(InputStream in=context.getAssets().open("turboio/card.schema.json");ByteArrayOutputStream o=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){if(o.size()+n>12000)throw new IOException();o.write(b,0,n);}schema=o.toString("UTF-8");}
        String system="仅返回单个JSON对象，不要Markdown。为256x194眼镜卡片生成布局，所有数据是用户指定或明确示例，不伪造真实账号额度。服从以下JSON schema。x/y/w/h必须为偶数，x+w<=250,y+h<=188，文字UTF8<=96字节，h>=font+4，每卡<=12组件、最多4图标/图片、2图表，总像素<=32768，编码<=2048字节。名称<=60UTF8字节。不可生成图片base64，用内置icon 0闪光1太阳2电脑3芯片4内存5硬盘6电池7云8书9音乐10位置11计时12心13完成14趋势15提醒。不得调用工具或接入数据源。\n"+schema;
        JSONObject body=new JSONObject().put("model",model).put("stream",false).put("temperature",0.2).put("max_tokens",4096).put("response_format",new JSONObject().put("type","json_object")).put("messages",new JSONArray().put(new JSONObject().put("role","system").put("content",system)).put(new JSONObject().put("role","user").put("content",prompt)));
        HttpURLConnection connection=(HttpURLConnection)new URL(endpoint).openConnection();connection.setInstanceFollowRedirects(false);connection.setConnectTimeout(15000);connection.setReadTimeout(45000);connection.setRequestMethod("POST");connection.setRequestProperty("Authorization","Bearer "+key);connection.setRequestProperty("Content-Type","application/json");connection.setDoOutput(true);try{byte[] data=body.toString().getBytes(StandardCharsets.UTF_8);connection.setFixedLengthStreamingMode(data.length);try(OutputStream out=connection.getOutputStream()){out.write(data);}int code=connection.getResponseCode();if(code!=200)throw new IOException("HTTP "+code);String result;try(InputStream in=connection.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){if(out.size()+n>65536)throw new IOException("响应超出预算");out.write(b,0,n);}result=out.toString("UTF-8");}JSONObject choice=new JSONObject(result).getJSONArray("choices").getJSONObject(0);if(!"stop".equals(choice.optString("finish_reason")))throw new IOException("模型响应不完整");String content=choice.getJSONObject("message").getString("content");Map<String,Object> doc=BoundedJson.map(BoundedJson.read(content.getBytes(StandardCharsets.UTF_8)));doc.put("id","turbo_ui_card_"+UUID.randomUUID().toString().replace("-",""));CardCodec.encode(doc,CardIcons::pixels);return doc;}finally{connection.disconnect();}}
}
