package com.turboio.addon;
import android.app.Activity;
import android.os.*;
import android.view.Gravity;
import android.widget.*;
import java.util.Locale;

final class FocusUI {
    static void show(Activity a){EditorialUI.Screen s=new EditorialUI.Screen(a,"番茄时钟");LinearLayout b=s.body;EditorialArt art=new EditorialArt(a,"focus-tomato-v2",false);b.addView(art,new LinearLayout.LayoutParams(-1,EditorialUI.dp(a,180)));TextView caption=EditorialUI.text(a,"这次，专注一件事",16,EditorialUI.MUTED);caption.setGravity(Gravity.CENTER);b.addView(caption);TextView time=EditorialUI.text(a,"25:00",60,EditorialUI.INK);time.setGravity(Gravity.CENTER);time.setTypeface(null,1);b.addView(time);final int[] seconds={1500};LinearLayout durations=new LinearLayout(a);b.addView(durations);for(int minutes:new int[]{15,25,45}){TextView t=EditorialUI.text(a,minutes+"分钟",16,EditorialUI.INK);t.setGravity(Gravity.CENTER);durations.addView(t,new LinearLayout.LayoutParams(0,EditorialUI.dp(a,48),1));t.setOnClickListener(v->{seconds[0]=minutes*60;if(FocusController.snapshot()==null||FocusController.snapshot().status==FocusCodec.IDLE||FocusController.snapshot().status==FocusCodec.STOPPED)time.setText(String.format(Locale.ROOT,"%02d:00",minutes));});}
        TextView status=EditorialUI.text(a,"",13,EditorialUI.MUTED);b.addView(status);EditorialUI.button(a,b,"开始专注 · 同步眼镜",true,()->EditorialUI.confirm(a,"开始眼镜独立计时？","请确认没有正在升级固件、录音、导航、音乐或阅读。关闭本页不会结束计时。",()->FocusController.start(seconds[0])));EditorialUI.button(a,b,"暂停 / 继续",false,()->{FocusCodec.Reply r=FocusController.snapshot();FocusController.operate(r!=null&&r.status==FocusCodec.PAUSED?FocusCodec.RESUME:FocusCodec.PAUSE);});EditorialUI.button(a,b,"结束本次计时",false,()->EditorialUI.confirm(a,"结束专注？","停止当前眼镜计时，不影响已完成记录。",()->FocusController.operate(FocusCodec.STOP)));EditorialUI.button(a,b,"查看 / 唤亮眼镜",false,()->FocusController.operate(FocusCodec.PEEK));EditorialUI.button(a,b,"刷新眼镜状态",false,FocusController::query);EditorialUI.gap(a,b,16);b.addView(EditorialUI.text(a,"眼镜独立计时，不持续亮屏。计时以眼镜回执为准；断连时手机的估算不代表执行成功。需要已安装 TFP1 或更新的兼容固件。",13,EditorialUI.MUTED));
        Runnable refresh=()->{status.setText(FocusController.status());FocusCodec.Reply r=FocusController.snapshot();if(r!=null){long sec=(r.status==FocusCodec.IDLE||r.status==FocusCodec.STOPPED)?seconds[0]:(FocusController.remaining()+999)/1000;time.setText(String.format(Locale.ROOT,"%02d:%02d",sec/60,sec%60));caption.setText(new String[]{"准备开始","专注中","已暂停","本轮完成","已结束"}[r.status]);}};FocusController.listen(refresh);NativeTransfer.listen(refresh);Handler h=new Handler(Looper.getMainLooper());Runnable tick=new Runnable(){public void run(){if(!s.dialog.isShowing())return;refresh.run();FocusController.refreshIfNeeded();h.postDelayed(this,1000);}};h.post(tick);s.dialog.setOnDismissListener(d->{h.removeCallbacks(tick);FocusController.detach();NativeTransfer.unlisten(refresh);});FocusController.query();
    }
}
