package com.turboio.addon;
import android.app.*;
import android.content.*;
import android.os.*;
import android.widget.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import static com.turboio.addon.BoundedJson.*;

final class GalleryUI {
    private static final ExecutorService IO=Executors.newSingleThreadExecutor();
    private static byte[] asset(Activity a,String name,int cap)throws IOException{try(InputStream in=a.getAssets().open("turboio/gallery/"+name);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){if(n>cap-out.size())throw new IOException();out.write(b,0,n);}return out.toByteArray();}}
    static void show(Activity a){EditorialUI.Screen s=new EditorialUI.Screen(a,"应用广场");LinearLayout tabs=new LinearLayout(a);s.body.addView(tabs);TextView state=EditorialUI.text(a,"",13,EditorialUI.MUTED);s.body.addView(state);LinearLayout content=EditorialUI.column(a);s.body.addView(content);int[] tab={0};
        Runnable slots=()->{state.setText(AppController.status());if(tab[0]!=0)return;content.removeAllViews();EditorialUI.button(a,content,"导入 SDK ZIP",true,()->DocumentPicker.pick(a,24576,bytes->openBytes(a,bytes)));EditorialUI.button(a,content,"重新查询眼镜四槽",false,AppController::query);AppCodec.Reply r=AppController.snapshot();for(int i=0;i<4;i++){int index=i;AppCodec.Slot item=r==null?null:r.slots[i];LinearLayout c=EditorialUI.card(a,content);c.addView(EditorialUI.text(a,"槽位 "+(i+1)+(r!=null&&r.activeSlot==i?" · 正在运行":""),13,EditorialUI.LIME));c.addView(EditorialUI.text(a,r==null?"等待眼镜返回":item==null?"空闲":item.name,20,EditorialUI.INK));if(item!=null){c.addView(EditorialUI.text(a,item.id+" · v"+item.version+(item.tombstone?" · 已移除记录":" · "+item.bytes+" 字节"),12,EditorialUI.MUTED));if(!item.tombstone){EditorialUI.button(a,c,"在眼镜打开",false,()->AppController.operate(AppCodec.LAUNCH,index,item));EditorialUI.button(a,c,"停止运行",false,()->AppController.operate(AppCodec.STOP,index,item));EditorialUI.button(a,c,"移除此应用",false,()->EditorialUI.confirm(a,"移除 "+item.name+"？","只移除当前槽位，不影响其他三个槽位。",()->AppController.operate(AppCodec.REMOVE,index,item)));}}}EditorialUI.gap(a,content,14);content.addView(EditorialUI.text(a,"只使用眼镜回读的槽位，不用手机缓存冒充安装结果。修改同一应用须提高 version。",13,EditorialUI.MUTED));};
        String[] names={"我的应用","应用广场","开发指南"};for(int i=0;i<3;i++){int target=i;TextView t=EditorialUI.text(a,names[i],15,EditorialUI.LIME);t.setGravity(android.view.Gravity.CENTER);tabs.addView(t,new LinearLayout.LayoutParams(0,EditorialUI.dp(a,50),1));t.setOnClickListener(v->{tab[0]=target;content.removeAllViews();if(target==0){slots.run();AppController.query();}else if(target==1)catalog(a,s,content,tab);else guide(a,content);});}
        Runnable changed=()->{state.setText(AppController.status());};NativeTransfer.listen(changed);AppController.listen(slots);s.dialog.setOnDismissListener(d->{tab[0]=-1;AppController.detach();NativeTransfer.unlisten(changed);});slots.run();AppController.query();
    }
    private static void guide(Activity a,LinearLayout b){b.addView(EditorialUI.text(a,"把自己的数据带到眼镜",24,EditorialUI.INK));EditorialUI.gap(a,b,12);b.addView(EditorialUI.text(a,"1 · 从广场选一个模板，复制开发提示词给 Agent。\n\n2 · MCP 跑在你自己的服务器；凭据不进入 ZIP 或眼镜。\n\n3 · SDK 校验并打包 app.json + manifest.json。ZIP ≤24 KiB，解压总计 ≤20 KiB，最多4页，单页12组件。\n\n4 · 手机导入 → 预览 → 查询四槽 → 确认安装。\n\n这是原生有界组件快照，不运行 JS / HTML；模板并不代表已经连接真实服务，也不承诺后台刷新或按钮服务端回流。",15,EditorialUI.MUTED));EditorialUI.button(a,b,"复制完整开发指南链接",true,()->copy(a,"https://github.com/Turbo1123/Turbo-IO/blob/main/docs/DEVELOPER_ECOSYSTEM.md"));}
    private static void copy(Activity a,String text){((ClipboardManager)a.getSystemService(Context.CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Turbo IO 开发",text));Toast.makeText(a,"已复制",Toast.LENGTH_SHORT).show();}
    private static void catalog(Activity a,EditorialUI.Screen screen,LinearLayout b,int[] tab){Object generation=new Object();b.setTag(generation);b.addView(EditorialUI.text(a,"20 个开发起点",24,EditorialUI.INK));b.addView(EditorialUI.text(a,"下方是离线样例，不是实时服务。点开可预览、安装或复制开发提示词。",13,EditorialUI.MUTED));IO.execute(()->{try{List<Object> entries=list(map(BoundedJson.read(asset(a,"catalog.json",65536))).get("entries"));for(Object o:entries){Map<String,Object> item=map(o);String resource=(String)item.get("resource");if(!resource.matches("Gallery_[a-z_]+"))throw new IOException();byte[] bytes=asset(a,resource+".zip",24576);AppCodec.Package pkg=AppCodec.read(bytes);if(!pkg.sha.equals(item.get("sha256")))throw new IOException();NativeTransfer.MAIN.post(()->{if(!screen.dialog.isShowing()||tab[0]!=1||b.getTag()!=generation)return;LinearLayout card=EditorialUI.card(a,b);card.addView(new AppPreview(a,pkg));EditorialUI.gap(a,card,10);card.addView(EditorialUI.text(a,(String)item.get("name"),20,EditorialUI.INK));card.addView(EditorialUI.text(a,item.get("category")+" · "+item.get("purpose"),13,EditorialUI.MUTED));EditorialUI.button(a,card,"预览与安装",false,()->preview(a,pkg,(String)item.get("prompt")));});}}catch(Exception e){NativeTransfer.MAIN.post(()->{if(screen.dialog.isShowing()&&tab[0]==1&&b.getTag()==generation)EditorialUI.notice(a,"内置样例校验失败，未发送任何内容");});}});}
    private static void openBytes(Activity a,byte[] bytes){IO.execute(()->{try{AppCodec.Package p=AppCodec.read(bytes);NativeTransfer.MAIN.post(()->{if(!a.isFinishing())preview(a,p,null);});}catch(Exception e){NativeTransfer.MAIN.post(()->EditorialUI.notice(a,"ZIP 不符合 SDK 契约或已损坏；未解压到磁盘，未发送眼镜。请用公开 SDK 重新构建。"));}});}
    private static void preview(Activity a,AppCodec.Package pkg,String prompt){EditorialUI.Screen s=new EditorialUI.Screen(a,pkg.name);s.body.addView(new AppPreview(a,pkg));EditorialUI.gap(a,s.body,14);s.body.addView(EditorialUI.text(a,"点预览切换页面 · 手机字体仅供布局参考\n"+pkg.id+" · v"+pkg.version+" · "+pkg.wire.length+" 字节\nSHA-256: "+pkg.sha,12,EditorialUI.MUTED));TextView status=EditorialUI.text(a,AppController.status(),13,EditorialUI.MUTED);s.body.addView(status);Runnable refresh=()->status.setText(AppController.status());NativeTransfer.listen(refresh);AppController.observe(refresh);s.dialog.setOnDismissListener(d->{NativeTransfer.unlisten(refresh);AppController.unobserve(refresh);});EditorialUI.button(a,s.body,"查询眼镜四槽",false,AppController::query);EditorialUI.button(a,s.body,"确认安装到眼镜",true,()->EditorialUI.confirm(a,"安装 "+pkg.name+"？","需要兼容 TAP1 的固件。请确认没有固件升级或其他任务；这是离线快照，不会自动接入 MCP。",()->AppController.install(pkg)));if(prompt!=null)EditorialUI.button(a,s.body,"复制给 Agent 的开发提示词",false,()->copy(a,prompt));}
}
