package com.turboio.addon;
import android.app.*;
import android.content.*;
import android.graphics.*;
import android.media.*;
import android.os.*;
import org.json.*;
import java.util.*;
import java.util.concurrent.*;

final class MusicPlayer {
 static final class Song{final long id,duration;final String title,artist,cover;Song(JSONObject j){id=j.optLong("id");duration=Math.max(0,Math.min(86400000,j.optLong("dt",j.optLong("duration"))));title=j.optString("name");JSONArray a=j.optJSONArray("ar");if(a==null)a=j.optJSONArray("artists");StringBuilder s=new StringBuilder();if(a!=null)for(int i=0;i<Math.min(a.length(),5);i++){if(s.length()>0)s.append(" / ");s.append(a.optJSONObject(i)==null?"":a.optJSONObject(i).optString("name"));}artist=s.toString();JSONObject album=j.optJSONObject("al");if(album==null)album=j.optJSONObject("album");cover=album==null?"":album.optString("picUrl");}}
 private static Context app;private static android.content.SharedPreferences prefs;private static MediaPlayer media;private static AudioManager audio;private static AudioFocusRequest focus;
 private static final ExecutorService IO=Executors.newFixedThreadPool(2);private static final Handler MAIN=new Handler(Looper.getMainLooper());private static final Set<Runnable> listeners=new HashSet<>();
 private static long ticket,displayToken,displayedTicket=-1;private static boolean prepared,wanted,foreground=true;private static String note="搜索可公开播放的歌曲，无需填 Key";private static Song song;private static List<Song> queue=new ArrayList<>();private static List<MusicCodec.Line> lines=new ArrayList<>();private static Bitmap artwork;private static byte[] mono;private static int mode=1;private static boolean sync;
 static void init(Context c){if(app!=null)return;app=c.getApplicationContext();prefs=app.getSharedPreferences("turboio_music_player",0);mode=prefs.getInt("mode",1);sync=prefs.getBoolean("sync",false);audio=(AudioManager)app.getSystemService(Context.AUDIO_SERVICE);BackgroundWork.register("音乐",()->play(false));BackgroundWork.register("音乐显示",MusicBridge::close);MusicBridge.init(app,new MusicBridge.Source(){public byte[] state(long event){return MusicCodec.state(position(),duration(),playing(),mode,event,song==null?"":song.title,song==null?"":song.artist);}public void command(int event){if(!sync)return;if(event==1&&song!=null){play(true);showOnGlasses();}else if(event==2)play(true);else if(event==3)play(false);else if(event==4)skip(1);else if(event==5)skip(-1);}});
  ((Application)app).registerActivityLifecycleCallbacks(new Application.ActivityLifecycleCallbacks(){public void onActivityStopped(Activity a){if(!a.isChangingConfigurations()&&a.getClass().getName().equals("com.rayneo.venus.MainActivity"))background();}public void onActivityCreated(Activity a,Bundle b){}public void onActivityStarted(Activity a){}public void onActivityResumed(Activity a){if(a.getClass().getName().equals("com.rayneo.venus.MainActivity")){foreground=true;BackgroundWork.onForeground(true);VoiceSpeech.foreground(true);}}public void onActivityPaused(Activity a){}public void onActivitySaveInstanceState(Activity a,Bundle b){}public void onActivityDestroyed(Activity a){}});
 }
 static void background(){foreground=false;BackgroundWork.onForeground(false);if(!BackgroundWork.held("音乐")&&!BackgroundWork.held("音乐显示")){displayToken++;play(false);if(MusicBridge.active())MusicBridge.close();}if(!BackgroundWork.held("阅读"))ReaderLibrary.stop();if(!BackgroundWork.held("新闻"))NewsTele.stop();if(!BackgroundWork.held("字幕"))CloudCaption.stop("离开前台，字幕已停止");VoiceSpeech.foreground(false);notifyUI();}
 static void listen(Runnable r){listeners.add(r);}static void unlisten(Runnable r){listeners.remove(r);}private static void notifyUI(){for(Runnable r:new ArrayList<>(listeners))r.run();}
 static String status(){return note+"\n"+MusicBridge.status();}static Song song(){return song;}static Bitmap artwork(){return artwork;}static List<MusicCodec.Line> lines(){return lines;}static boolean sync(){return sync;}static int mode(){return mode;}
 static void mode(int n){mode=Math.max(0,Math.min(2,n));prefs.edit().putInt("mode",mode).apply();MusicBridge.changed();}
 static void sync(boolean on){sync=on;displayToken++;prefs.edit().putBoolean("sync",on).apply();if(!on)MusicBridge.close();else if(song!=null)showOnGlasses();notifyUI();}
 interface Results{void done(List<Song> songs,String error);}
 static void search(String text,Results result){if(text.trim().isEmpty()||text.length()>100){result.done(Collections.emptyList(),"请输入不超过100字的歌名或歌手");return;}IO.execute(()->{List<Song> out=new ArrayList<>();String error=null;try{JSONObject r=MusicApi.request("/api/cloudsearch/pc",new JSONObject().put("s",text.trim()).put("type",1).put("limit",20).put("offset",0).put("total",true),false).optJSONObject("result");JSONArray songs=r==null?null:r.optJSONArray("songs");if(songs!=null)for(int i=0;i<Math.min(20,songs.length());i++){JSONObject j=songs.optJSONObject(i);if(j!=null){Song s=new Song(j);if(s.id>0&&!s.title.isEmpty())out.add(s);}}}catch(Exception e){error="搜索失败或服务限制；未绕过登录/地区/会员限制";}String err=error;MAIN.post(()->result.done(out,err));});}
 static long position(){try{return prepared&&media!=null?Math.min(86400000,media.getCurrentPosition()):0;}catch(RuntimeException e){return 0;}}static long duration(){try{return prepared&&media!=null?Math.max(0,Math.min(86400000,media.getDuration())):song==null?0:song.duration;}catch(RuntimeException e){return song==null?0:song.duration;}}static boolean playing(){try{return prepared&&media!=null&&media.isPlaying();}catch(RuntimeException e){return false;}}
 private static void release(){if(media!=null){media.release();media=null;}prepared=false;BackgroundWork.release("音乐");if(focus!=null){audio.abandonAudioFocusRequest(focus);focus=null;}}
 static void select(Song s,List<Song> list){if(MusicBridge.busy()){note="眼镜正在传输，请稍候再切歌";notifyUI();return;}long t=++ticket;displayedTicket=-1;release();VoiceSpeech.stop("音乐开始，停止回答朗读");song=s;queue=new ArrayList<>(list.subList(0,Math.min(100,list.size())));lines=new ArrayList<>();artwork=null;mono=null;wanted=true;note="获取可播放地址";notifyUI();
  // Retire the old visual state before opening the selected track. Metadata
  // display does not wait for audio/network preparation. onPrepared updates
  // an existing session, never retries a rejected OPEN behind the user's back.
  if(MusicBridge.active())MusicBridge.close();
  if(sync)showOnGlasses();
  IO.execute(()->{try{JSONArray rows=MusicApi.request("/api/song/enhance/player/url/v1",new JSONObject().put("ids","["+s.id+"]").put("level","standard").put("encodeType","aac"),true).optJSONArray("data");JSONObject r=rows==null?null:rows.optJSONObject(0);String url=r==null?"":MusicApi.mediaURL(r.optString("url"));if(url.isEmpty())throw new MusicApi.Failure(r==null?"播放地址响应缺少歌曲数据":r.optString("url").isEmpty()?"服务未返回可播放地址（可能受账号或曲目权限限制）":"播放地址格式不兼容，未请求该地址");boolean trial=r.has("freeTrialInfo")&&!r.isNull("freeTrialInfo");MAIN.post(()->{if(t==ticket)install(url,t,trial);});}catch(Exception e){MAIN.post(()->{if(t==ticket){note=MusicApi.error(e)+"；封面与歌词仍可单独同步";notifyUI();}});}});
  IO.execute(()->{List<MusicCodec.Line> parsed;try{JSONObject l=MusicApi.request("/api/song/lyric",new JSONObject().put("id",s.id).put("lv",-1).put("kv",-1).put("tv",-1),false).optJSONObject("lrc");parsed=MusicCodec.lrc(l==null?"":l.optString("lyric"));}catch(Exception e){parsed=new ArrayList<>();}if(parsed.isEmpty())parsed=Arrays.asList(new MusicCodec.Line(0,"暂无歌词或歌词获取失败"));List<MusicCodec.Line> result=parsed;MAIN.post(()->{if(t==ticket){lines=result;if(sync||MusicBridge.active())MusicBridge.assets(mono,lines);notifyUI();}});
   try{byte[] bytes=MusicApi.image(s.cover);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);if(o.outWidth<=0||o.outHeight<=0||(long)o.outWidth*o.outHeight>40000000)throw new IllegalStateException();o.inJustDecodeBounds=false;o.inSampleSize=1;while(Math.max(o.outWidth,o.outHeight)/o.inSampleSize>600)o.inSampleSize*=2;Bitmap original=BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);if(original==null)throw new IllegalStateException();int side=Math.min(original.getWidth(),original.getHeight());Bitmap crop=Bitmap.createBitmap(original,(original.getWidth()-side)/2,(original.getHeight()-side)/2,side,side);Bitmap square=Bitmap.createScaledBitmap(crop,144,144,true);int[] px=new int[20736];square.getPixels(px,0,144,0,0,144,144);byte[] luminance=new byte[20736];for(int i=0;i<px.length;i++)luminance[i]=(byte)(((Color.red(px[i])*54+Color.green(px[i])*183+Color.blue(px[i])*19)>>8)*Color.alpha(px[i])/255);MAIN.post(()->{if(t==ticket){artwork=square;mono=luminance;if(sync||MusicBridge.active())MusicBridge.assets(mono,lines);notifyUI();}});}catch(Exception ignored){MAIN.post(()->{if(t==ticket){note+=" · 封面不可用";notifyUI();}});}
  });
 }
 private static void install(String url,long t,boolean trial){try{media=new MediaPlayer();MediaPlayer p=media;p.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_MEDIA).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build());p.setDataSource(app,android.net.Uri.parse(url),Collections.singletonMap("Referer","https://music.163.com"));p.setOnPreparedListener(m->{if(t!=ticket||m!=media)return;prepared=true;note=trial?"正在试听（服务端返回的可播放范围）":"已就绪";if(wanted)play(true);if(sync&&MusicBridge.active())MusicBridge.changed();notifyUI();});p.setOnCompletionListener(m->{if(m==media){wanted=false;BackgroundWork.release("音乐");MusicBridge.changed();note="本曲播放结束";notifyUI();}});p.setOnErrorListener((m,w,e)->{if(t==ticket){release();note="音频加载/解码失败";notifyUI();}return true;});p.prepareAsync();}catch(Exception e){release();note="播放器启动失败";notifyUI();}}
 static void play(boolean on){if(on&&!foreground&&!BackgroundWork.held("音乐")&&!BackgroundWork.held("音乐显示")){note="当前是前台测试版，请先打开手机 App";notifyUI();return;}wanted=on;if(!prepared||media==null){notifyUI();return;}try{if(on){VoiceSpeech.stop("音乐播放，停止回答朗读");if(focus==null){focus=new AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN).setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_MEDIA).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build()).setOnAudioFocusChangeListener(change->{if(change<0)MAIN.post(()->play(false));},MAIN).build();}if(audio.requestAudioFocus(focus)!=AudioManager.AUDIOFOCUS_REQUEST_GRANTED){note="未获得媒体音频焦点";notifyUI();return;}BackgroundWork.acquire("音乐",2);media.start();note="播放中";}else{media.pause();BackgroundWork.release("音乐");note="已暂停";if(focus!=null){audio.abandonAudioFocusRequest(focus);focus=null;}}MusicBridge.changed();notifyUI();}catch(RuntimeException e){note="播放状态变化，无法操作";notifyUI();}}
 static void seek(long ms){if(!prepared||media==null)return;media.seekTo(Math.max(0,Math.min(duration(),ms)),MediaPlayer.SEEK_CLOSEST);MusicBridge.changed();}
 static void skip(int d){if(song==null||queue.isEmpty())return;int i=queue.indexOf(song);int n=i+d;if(n<0||n>=queue.size()){note="已到列表边界";notifyUI();return;}select(queue.get(n),queue);}
 static void showOnGlasses(){showOnGlasses(ticket,++displayToken,0);}
 private static void showOnGlasses(long t,long display,int wait){if(t!=ticket||display!=displayToken||!foreground)return;if(song==null){note="请先选择歌曲";notifyUI();return;}
  if(displayedTicket==t&&MusicBridge.active()){MusicBridge.changed();return;}
  if(MusicBridge.busy()||MusicBridge.active()){if(wait>=20){note="上一眼镜命令仍未结束，请确认状态后手动同步";notifyUI();return;}MAIN.postDelayed(()->showOnGlasses(t,display,wait+1),1000);return;}
  MusicBridge.open(mono,lines);if(MusicBridge.active())displayedTicket=t;notifyUI();}
 static void testDisplay(){
  if(MusicBridge.busy()||NativeTransfer.busy()){note="通道忙碌，请等当前操作结束";notifyUI();return;}
  try{ticket++;displayedTicket=-1;release();wanted=false;song=new Song(new JSONObject().put("id",0).put("name","Turbo IO 音乐测试 7392").put("dt",60000));queue=new ArrayList<>();lines=Arrays.asList(new MusicCodec.Line(0,"这是一张离线同步测试卡"),new MusicCodec.Line(10000,"测试封面、标题与五行歌词"),new MusicCodec.Line(20000,"不请求网易云、不播放声音"));
   mono=new byte[MusicCodec.COVER_BYTES];int[] px=new int[mono.length];for(int y=0;y<144;y++)for(int x=0;x<144;x++){int dx=x-72,dy=y-72;int v=dx*dx+dy*dy<4400?(((x/18+y/18)%2==0)?220:80):0;mono[y*144+x]=(byte)v;px[y*144+x]=Color.rgb(v,v,v);}artwork=Bitmap.createBitmap(px,144,144,Bitmap.Config.ARGB_8888);
   if(MusicBridge.active())MusicBridge.close();note="离线测试卡 · 无声音";showOnGlasses();notifyUI();
  }catch(JSONException e){note="测试卡构建失败";notifyUI();}
 }
 static void closeDisplay(){displayToken++;displayedTicket=-1;MusicBridge.close();}
}
