package com.turboio.addon;
import org.json.*;
import java.net.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.math.BigInteger;
import java.util.*;
import javax.crypto.*;
import javax.crypto.spec.*;

/** API compatibility adapted from Beans Music (MIT, XIaodou0416, 2026).
 * See android-addon/THIRD_PARTY_MUSIC_LICENSE.txt. No VIP/region/DRM bypass.
 * Guest-only in this iteration: no cookies imported or silently copied. */
final class MusicApi {
 static final class Failure extends IOException {Failure(String reason){super(reason);}}
 static String error(Exception e){if(e instanceof Failure)return e.getMessage();if(e instanceof java.net.SocketTimeoutException)return "音乐服务请求超时";if(e instanceof java.net.UnknownHostException)return "音乐服务域名无法解析";if(e instanceof javax.net.ssl.SSLException)return "音乐服务 TLS 连接失败";if(e instanceof JSONException)return "音乐服务返回格式异常";if(e instanceof IOException)return "音乐服务网络请求失败";return "音乐请求处理失败";}
 static String hex(byte[] b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format(Locale.ROOT,"%02x",x&255));return s.toString();}
 private static byte[] aes(byte[] b,byte[] key,boolean ecb)throws Exception{Cipher c=Cipher.getInstance(ecb?"AES/ECB/PKCS5Padding":"AES/CBC/PKCS5Padding");SecretKeySpec k=new SecretKeySpec(key,"AES");if(ecb)c.init(Cipher.ENCRYPT_MODE,k);else c.init(Cipher.ENCRYPT_MODE,k,new IvParameterSpec("0102030405060708".getBytes(StandardCharsets.US_ASCII)));return c.doFinal(b);}
 static Map<String,String> encrypt(String json,String path,boolean eapi)throws Exception{byte[] j=json.getBytes(StandardCharsets.UTF_8);Map<String,String> out=new TreeMap<>();
  if(eapi){String digest=hex(MessageDigest.getInstance("MD5").digest(("nobody"+path+"use"+json+"md5forencrypt").getBytes(StandardCharsets.UTF_8)));String plain=path+"-36cd479b6b5-"+json+"-36cd479b6b5-"+digest;out.put("params",hex(aes(plain.getBytes(StandardCharsets.UTF_8),"e82ckenh8dichen8".getBytes(StandardCharsets.US_ASCII),true)));}
  else{byte[] key=new byte[16];String alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";SecureRandom rng=new SecureRandom();for(int i=0;i<16;i++)key[i]=(byte)alphabet.charAt(rng.nextInt(alphabet.length()));byte[] one=aes(j,"0CoJUm6Qyw8W8jud".getBytes(StandardCharsets.US_ASCII),false);out.put("params",Base64.getEncoder().encodeToString(aes(Base64.getEncoder().encode(one),key,false)));byte[] reverse=new byte[16];for(int i=0;i<16;i++)reverse[i]=key[15-i];BigInteger modulus=new BigInteger("e0b509f6259df8642dbc35662901477df22677ec152b5ff68ace615bb7b725152b3ab17a876aea8a5aa76d2e417629ec4ee341f56135fccf695280104e0312ecbda92557c93870114af6c9d05c4f7f0c3685b7a46bee255932575cce10b424d813cfe4875d3e82047b97ddef52741d546b8e289dc6935b3ece0462db0a22b8e7",16);out.put("encSecKey",String.format(Locale.ROOT,"%0256x",new BigInteger(1,reverse).modPow(BigInteger.valueOf(65537),modulus)));}return out;
 }
 static JSONObject request(String path,JSONObject input,boolean eapi)throws Exception{if(!Arrays.asList("/api/cloudsearch/pc","/api/song/enhance/player/url/v1","/api/song/lyric","/api/v6/playlist/detail").contains(path))throw new IOException("Unsupported endpoint");JSONObject body=new JSONObject(input.toString());if(eapi){body.put("header",new JSONObject().put("os","pc").put("appver","3.1.17.204416").put("deviceId","TurboIO").put("__csrf","").put("channel","netease").put("requestId",UUID.randomUUID().toString())).put("e_r",false);}else body.put("csrf_token","");Map<String,String> encrypted=encrypt(body.toString(),path,eapi);StringBuilder form=new StringBuilder();for(Map.Entry<String,String> pair:encrypted.entrySet()){if(form.length()>0)form.append('&');form.append(pair.getKey()).append('=').append(URLEncoder.encode(pair.getValue(),"UTF-8"));}
  URL url=new URL((eapi?"https://interface.music.163.com/eapi":"https://music.163.com/weapi")+path.substring(4));HttpURLConnection c=(HttpURLConnection)url.openConnection();try{c.setInstanceFollowRedirects(false);c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/x-www-form-urlencoded");c.setRequestProperty("Referer","https://music.163.com");c.setRequestProperty("User-Agent",eapi?"NeteaseMusic 9.0.90/5038 (iPhone; iOS 16.2; zh_CN)":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/124.0.0.0 Safari/537.36");if(eapi){JSONObject h=body.getJSONObject("header");StringBuilder cookies=new StringBuilder();for(String k:new String[]{"os","appver","deviceId","__csrf","channel","requestId"})cookies.append(k).append('=').append(h.getString(k)).append("; ");c.setRequestProperty("Cookie",cookies.toString());}byte[] data=form.toString().getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(data.length);try(OutputStream out=c.getOutputStream()){out.write(data);}if(c.getResponseCode()!=200)throw new Failure("音乐服务 HTTP "+c.getResponseCode());JSONObject result=new JSONObject(new String(read(c.getInputStream(),4*1024*1024),StandardCharsets.UTF_8));if(result.optInt("code",200)!=200)throw new Failure("音乐服务拒绝，code="+result.optInt("code"));return result;}finally{c.disconnect();}
 }
 static byte[] read(InputStream in,int max)throws IOException{try(InputStream stream=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=stream.read(b))!=-1){if(n>max-out.size())throw new IOException("Response limit");out.write(b,0,n);}return out.toByteArray();}}
 static String mediaURL(String value){try{URI u=new URI(value);String h=u.getHost();if(h==null||u.getUserInfo()!=null||u.getFragment()!=null||(u.getPort()!=-1&&u.getPort()!=443))return "";h=h.toLowerCase(Locale.ROOT);if(!(h.endsWith(".music.126.net")||h.endsWith(".music.163.com")||h.equals("music.163.com")))return "";if(!u.getScheme().equals("https")&&!u.getScheme().equals("http"))return "";return "https"+value.substring(value.indexOf(':'));}catch(Exception e){return "";}}
 static byte[] image(String value)throws Exception{String allowed=mediaURL(value);if(allowed.isEmpty())throw new IOException("Image host not allowed");HttpURLConnection c=(HttpURLConnection)new URL(allowed).openConnection();try{c.setInstanceFollowRedirects(false);c.setConnectTimeout(10000);c.setReadTimeout(15000);if(c.getResponseCode()!=200)throw new IOException("Cover unavailable");return read(c.getInputStream(),2*1024*1024);}finally{c.disconnect();}}
}
