package com.turboio.addon;
import android.app.*;
import android.graphics.Typeface;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;

final class MusicUI {
 static void show(Activity a){MusicPlayer.init(a);EditorialUI.Screen screen=new EditorialUI.Screen(a,"网易云音乐");LinearLayout b=screen.body;
  b.addView(EditorialUI.text(a,"音乐随行",28,EditorialUI.INK));b.addView(EditorialUI.text(a,"可播放服务端返回的公开曲目\n无登录绕过，不支持下载；后台运行可在设置中开启。",13,EditorialUI.MUTED));
  EditText search=new EditText(a);search.setSingleLine(true);search.setTextColor(EditorialUI.INK);search.setHintTextColor(EditorialUI.MUTED);search.setHint("搜索歌曲 / 歌手");search.setBackground(EditorialUI.shape(a,EditorialUI.SURFACE,18));search.setPadding(EditorialUI.dp(a,16),EditorialUI.dp(a,14),EditorialUI.dp(a,16),EditorialUI.dp(a,14));b.addView(search);LinearLayout results=EditorialUI.column(a);
  TextView state=EditorialUI.text(a,"",14,EditorialUI.MUTED),searchState=EditorialUI.text(a,"",13,EditorialUI.MUTED);int[] request={0};boolean[] showing={true},searching={false};
  EditorialUI.button(a,b,"搜索",false,()->{if(searching[0])return;searching[0]=true;int ticket=++request[0];searchState.setText("正在搜索…");MusicPlayer.search(search.getText().toString(),(songs,error)->{searching[0]=false;if(!showing[0]||ticket!=request[0])return;results.removeAllViews();if(error!=null){searchState.setText(error);return;}searchState.setText("找到 "+songs.size()+" 首；点击播放");for(MusicPlayer.Song s:songs)EditorialUI.button(a,results,s.title+" · "+s.artist,false,()->{MusicPlayer.select(s,songs);results.removeAllViews();searchState.setText("已选择 · "+s.title);});});});b.addView(searchState);b.addView(results);
  ImageView cover=new ImageView(a);cover.setScaleType(ImageView.ScaleType.FIT_CENTER);FrameLayout artBox=new FrameLayout(a);EditorialArt placeholder=new EditorialArt(a,"music",false);artBox.addView(placeholder,new FrameLayout.LayoutParams(-1,-1));artBox.addView(cover,new FrameLayout.LayoutParams(-1,-1));LinearLayout.LayoutParams art=new LinearLayout.LayoutParams(-1,EditorialUI.dp(a,210));art.topMargin=EditorialUI.dp(a,16);b.addView(artBox,art);
  TextView title=EditorialUI.text(a,"选择一首歌，抬头看歌词",23,EditorialUI.INK),artist=EditorialUI.text(a,"",14,EditorialUI.MUTED);title.setTypeface(null,Typeface.BOLD);b.addView(title);b.addView(artist);b.addView(state);
  SeekBar seek=new SeekBar(a);seek.setMax(1000);styleSeek(a,seek);b.addView(seek,new LinearLayout.LayoutParams(-1,EditorialUI.dp(a,48)));TextView clock=EditorialUI.text(a,"00:00 / 00:00",13,EditorialUI.MUTED);b.addView(clock);boolean[] dragging={false};seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){dragging[0]=true;}public void onStopTrackingTouch(SeekBar s){MusicPlayer.seek(MusicPlayer.duration()*s.getProgress()/1000);dragging[0]=false;}public void onProgressChanged(SeekBar s,int p,boolean user){}});
  LinearLayout controls=new LinearLayout(a);b.addView(controls);for(int i=0;i<3;i++){final int op=i;TextView t=EditorialUI.text(a,new String[]{"上一首","播放 / 暂停","下一首"}[i],15,EditorialUI.INK);t.setGravity(Gravity.CENTER);t.setBackground(EditorialUI.shape(a,EditorialUI.SURFACE,24));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,EditorialUI.dp(a,56),1);p.setMargins(4,8,4,8);controls.addView(t,p);t.setOnClickListener(v->{if(op==1)MusicPlayer.play(!MusicPlayer.playing());else MusicPlayer.skip(op==0?-1:1);});}
  LinearLayout lyricBox=EditorialUI.card(a,b);TextView[] lyrics=new TextView[5];for(int i=0;i<5;i++){lyrics[i]=EditorialUI.text(a,"",i==2?21:16,i==2?EditorialUI.LIME:EditorialUI.MUTED);lyrics[i].setGravity(Gravity.CENTER);lyrics[i].setMaxLines(2);lyrics[i].setEllipsize(android.text.TextUtils.TruncateAt.END);lyricBox.addView(lyrics[i],new LinearLayout.LayoutParams(-1,EditorialUI.dp(a,60)));}
  LinearLayout syncControls=EditorialUI.card(a,b);b.removeView(syncControls);b.addView(syncControls,2);b.removeView(state);syncControls.addView(state);
  EditorialUI.toggle(a,syncControls,"自动同步封面与歌词到眼镜（TMU1）",MusicPlayer.sync(),(v,on)->MusicPlayer.sync(on));
  EditorialUI.button(a,b,"眼镜显示时长",false,()->new AlertDialog.Builder(a).setTitle("音乐画面显示时长").setSingleChoiceItems(new String[]{"一直显示","30 秒","1 分钟"},MusicPlayer.mode(),(d,w)->{MusicPlayer.mode(w);d.dismiss();}).setNegativeButton("取消",null).show());
  EditorialUI.button(a,syncControls,"显示到眼镜 / 重新进入",true,MusicPlayer::showOnGlasses);EditorialUI.button(a,syncControls,"退出眼镜音乐画面",false,MusicPlayer::closeDisplay);
  EditorialUI.button(a,b,"离线同步测试 7392（无声音）",false,()->EditorialUI.confirm(a,"测试眼镜音乐通道？","不访问音乐服务；将暂停当前手机音乐，发送原创测试封面和文字。请确保眼镜无其他显示任务。",MusicPlayer::testDisplay));
  EditorialUI.button(a,b,"确认眼镜已回首页",false,()->EditorialUI.confirm(a,"仅在实际退出后确认","不会强制关闭眼镜画面；请先目视确认眼镜已回首页。",MusicBridge::resetAfterUserConfirmation));
  Runnable refresh=()->{MusicPlayer.Song s=MusicPlayer.song();if(s!=null){title.setText(s.title);artist.setText(s.artist);}cover.setImageBitmap(MusicPlayer.artwork());placeholder.setVisibility(MusicPlayer.artwork()==null?View.VISIBLE:View.GONE);setText(state,MusicPlayer.status());};MusicPlayer.listen(refresh);Handler h=new Handler(Looper.getMainLooper());Runnable tick=new Runnable(){public void run(){if(!showing[0])return;long p=MusicPlayer.position(),d=MusicPlayer.duration();setText(clock,time(p)+" / "+time(d));if(!dragging[0])seek.setProgress(d==0?0:(int)(p*1000/d));List<MusicCodec.Line> rows=MusicPlayer.lines();int row=MusicCodec.line(rows,p);for(int i=0;i<5;i++){int at=row+i-2;setText(lyrics[i],at<0||at>=rows.size()?"":rows.get(at).text);}setText(state,MusicPlayer.status());h.postDelayed(this,400);}};refresh.run();h.post(tick);screen.dialog.setOnDismissListener(v->{showing[0]=false;request[0]++;MusicPlayer.unlisten(refresh);h.removeCallbacks(tick);});
 }
 private static void setText(TextView v,String value){if(!value.contentEquals(v.getText()))v.setText(value);}
 private static void styleSeek(Activity a,SeekBar s){android.graphics.drawable.GradientDrawable back=EditorialUI.shape(a,0xff554d57,4),fill=EditorialUI.shape(a,EditorialUI.LIME,4),thumb=EditorialUI.shape(a,EditorialUI.INK,10);thumb.setSize(EditorialUI.dp(a,16),EditorialUI.dp(a,16));android.graphics.drawable.ClipDrawable clip=new android.graphics.drawable.ClipDrawable(fill,Gravity.LEFT,android.graphics.drawable.ClipDrawable.HORIZONTAL);android.graphics.drawable.LayerDrawable layers=new android.graphics.drawable.LayerDrawable(new android.graphics.drawable.Drawable[]{back,clip});layers.setId(0,android.R.id.background);layers.setId(1,android.R.id.progress);for(int i=0;i<2;i++){layers.setLayerHeight(i,EditorialUI.dp(a,4));layers.setLayerGravity(i,Gravity.CENTER_VERTICAL|Gravity.FILL_HORIZONTAL);}s.setProgressDrawable(layers);s.setThumb(thumb);s.setSplitTrack(false);s.setPadding(EditorialUI.dp(a,10),0,EditorialUI.dp(a,10),0);}
 private static String time(long ms){return String.format(java.util.Locale.ROOT,"%02d:%02d",ms/60000,(ms/1000)%60);}
}
