package com.turboio.addon;
import java.util.*;

/** Route-search approximation, not AMap's turn-by-turn navigation engine. */
public final class NativeNavRoute {
    private static double length(List<NavCore.Point> p){double n=0;for(int i=1;i<p.size();i++)n+=NavCore.distance(p.get(i-1),p.get(i));return n;}
    public static int icon(String instruction){String s=instruction.toLowerCase(Locale.ROOT);if(s.contains("掉头")||s.contains("调头")||s.contains("u-turn"))return 8;if(s.contains("环岛")||s.contains("roundabout"))return 9;if(s.contains("左后")||s.contains("sharp left"))return 6;if(s.contains("右后")||s.contains("sharp right"))return 7;if(s.contains("左前")||s.contains("slight left"))return 4;if(s.contains("右前")||s.contains("slight right"))return 5;if(s.contains("左转")||s.contains("turn left"))return 2;if(s.contains("右转")||s.contains("turn right"))return 3;if(s.contains("直行")||s.contains("straight"))return 1;return 0;}
    public static NativeNavCodec.Scene scene(List<NavCore.Step> steps,int at,NavCore.Point position,double remainingStep,long totalSeconds,boolean simulated,boolean always,boolean arrived){if(steps==null||steps.isEmpty()||steps.size()>4096||at<0||at>=steps.size()||position==null||!Double.isFinite(remainingStep)||remainingStep<0||totalSeconds<0)throw new IllegalArgumentException();NativeNavCodec.Scene s=new NativeNavCodec.Scene();s.mode=always?1:0;s.icon=arrived?10:icon(steps.get(at).instruction);s.turn=NativeNavCodec.clip(arrived?"已接近目的地":steps.get(at).instruction,48);s.road=NativeNavCodec.clip((simulated?"模拟 · ":"")+"路线估算 · "+(at+1)+"/"+steps.size()+"段",96);s.distance=Math.min(1000000,Math.round(remainingStep));double remaining=remainingStep,total=0;for(int i=0;i<steps.size();i++){double len=length(steps.get(i).points);total+=len;if(i>at)remaining+=len;}s.remaining=arrived?0:Math.min(10000000,Math.round(remaining));s.seconds=arrived?0:Math.min(604800,Math.max(0,Math.round(totalSeconds*Math.min(1,remaining/Math.max(1,total)))));
        // Whole route, bounded sampling, north-up; no raster images or GPS values on wire.
        List<NavCore.Point> points=new ArrayList<>();int all=0;for(NavCore.Step step:steps)all+=step.points.size();if(all>100000)throw new IllegalArgumentException();int stride=Math.max(1,(all+29)/30),index=0;for(NavCore.Step step:steps)for(NavCore.Point p:step.points)if(index++%stride==0&&points.size()<31)points.add(p);NavCore.Point end=steps.get(steps.size()-1).points.get(steps.get(steps.size()-1).points.size()-1);points.add(end);
        double scale=Math.max(.01,Math.cos(Math.toRadians(position.lat))),minX=position.lon*scale,maxX=minX,minY=position.lat,maxY=minY;for(NavCore.Point p:points){minX=Math.min(minX,p.lon*scale);maxX=Math.max(maxX,p.lon*scale);minY=Math.min(minY,p.lat);maxY=Math.max(maxY,p.lat);}double span=Math.max(.00001,Math.max(maxX-minX,maxY-minY));double ox=(minX+maxX)/2-span/2,oy=(minY+maxY)/2-span/2;s.points=new int[points.size()][2];for(int i=0;i<points.size();i++){s.points[i][0]=norm((points.get(i).lon*scale-ox)/span);s.points[i][1]=1023-norm((points.get(i).lat-oy)/span);}s.x=norm((position.lon*scale-ox)/span);s.y=1023-norm((position.lat-oy)/span);return s;
    }
    private static int norm(double n){return (int)Math.max(0,Math.min(1023,Math.round(n*1023)));}
}
