package com.turboio.addon;
import android.os.*;import java.util.*;import java.nio.charset.StandardCharsets;import org.json.*;
/** Official business20: fresh DID, FNV-1a, two receipts, no official script mutation. */
final class NewsTele {
 private static String did="",peer="",phase="idle",note="尚未发送新闻稿";private static byte[] text;private static int speed;private static long deadline;private static boolean fileStarted;private static int waiting;
 static String status(){return note;}static boolean active(){return !did.isEmpty();}
 static String checksum(byte[] b){long h=2166136261L;for(byte v:b)h=((h^(v&255))*16777619L)&0xffffffffL;return String.format(Locale.ROOT,"%08x",h);}
 static void start(String content,int value){if(active()){note="请先结束上一新闻会话";return;}text=content.getBytes(StandardCharsets.UTF_8);if(content.length()>12000||text.length<1||text.length>48000||value<60||value>1200){note="稿件/速度超出限制";return;}String owner=UUID.randomUUID().toString();if(!NativeTransfer.acquireMessages(owner)){note="请先连接眼镜并结束其他显示/传输任务";return;}did=owner;peer=NativeTransfer.connected();speed=value;fileStarted=false;phase="prepare";waiting=2;deadline=SystemClock.elapsedRealtime()+15000;note="准备新闻稿，等待眼镜允许传稿";BackgroundWork.acquire("新闻",16);try{send(2,config(false));}catch(Exception e){fail("准备请求未确认");}NativeTransfer.MAIN.removeCallbacks(tick);NativeTransfer.MAIN.postDelayed(tick,250);}
 private static JSONObject config(boolean start)throws Exception{JSONObject j=new JSONObject().put("action",1).put("did",did).put("total",text.length).put("scroll",2).put("speed",speed).put("countdown",3).put("gear",3).put("depth",1).put("size",18).put("width",492).put("leading",4).put("pageOffset",0).put("highLightOffset",0);if(start)j.put("checksum",checksum(text)).put("code",1);return j;}
 private static void send(int type,JSONObject j)throws Exception{if(!peer.equals(NativeTransfer.connected()))throw new IllegalStateException();Object manager=NavReflect.field(NavReflect.type("E3.u"),"h"),biz=NavReflect.call(NavReflect.type("P3.h"),"valueOf","TELEPROMPTER"),priority=NavReflect.call(NavReflect.type("E3.b"),"valueOf","NORMAL");String owner=did;Object message=NavReflect.make("E3.Q",OtaFrame.encode(type,BoundedJson.read(j.toString().getBytes(StandardCharsets.UTF_8)),null),UUID.randomUUID().toString(),peer,biz,null,priority,false,false,null,null);Object callback=NavReflect.proxy("kotlin.jvm.functions.Function2",(n,args)->{if(args.length>1&&args[1]!=null)NativeTransfer.MAIN.post(()->{if(did.equals(owner))fail("SDK拒绝新闻控制；请确认镜片状态");});});NavReflect.call(manager,"u",message,callback);}
 static void control(int type){if(!active()||!(type==3||type==4||type==5||type==6||type==7)||waiting!=0&&type!=6)return;if(type==3&&!phase.equals("ready"))return;try{JSONObject j=type==3?config(true):new JSONObject().put("action",1).put("did",did);if(type==4)j.put("offset",0).put("code",1).put("isCompleted",false);if(type==7)j.put("scroll",2).put("speed",speed);waiting=type;deadline=SystemClock.elapsedRealtime()+10000;if(type==6)phase="closing";send(type,j);NativeTransfer.MAIN.removeCallbacks(tick);NativeTransfer.MAIN.postDelayed(tick,250);note="控制已提交，等待眼镜确认";}catch(Exception e){fail("新闻控制未确认");}}
 static void stop(){control(6);}static void reset(){if(!phase.equals("uncertain")||NativeTransfer.fileBusy())return;clear();note="已由用户确认镜片退出";}
 private static void fail(String s){phase="uncertain";waiting=0;note=s+"；未自动重试，可从眼镜退出后确认恢复";BackgroundWork.release("新闻");NativeTransfer.MAIN.removeCallbacks(tick);}
 private static void clear(){NativeTransfer.releaseMessages(did);did="";text=null;phase="idle";waiting=0;BackgroundWork.release("新闻");NativeTransfer.MAIN.removeCallbacks(tick);}
 private static final Runnable tick=new Runnable(){public void run(){if(!active()||phase.equals("uncertain"))return;if(!peer.equals(NativeTransfer.connected()))fail("眼镜连接发生变化");else if(waiting!=0&&SystemClock.elapsedRealtime()>=deadline)fail("新闻回执超时");if(active()&&!phase.equals("uncertain"))NativeTransfer.MAIN.postDelayed(this,250);}};
 static void receive(String d,byte[] b){if(!active()||!peer.equals(d))return;try{NavCore.Envelope e=NavCore.decode(b);if(e==null)return;if(e.type==9){stop();return;}JSONObject j=new JSONObject(e.json);if(!did.equals(j.optString("did")))return;int action=j.optInt("action"),code=j.optInt("code",-1);
  if(e.type==6&&(action==1||action==2&&code==1)){if(action==1)send(6,new JSONObject().put("did",did).put("action",2).put("code",1));clear();note="眼镜已退出；新闻稿保留在手机";return;}
  if(e.type==8&&action==1){send(8,new JSONObject().put("did",did).put("action",2).put("code",1));return;}
  if(e.type==2&&action==2&&waiting==2){if(j.has("total")&&j.optInt("total")!=text.length)return;if(code!=1&&code!=7){fail("眼镜拒绝准备（"+code+"）");return;}
   if(!fileStarted){if(code!=1){fail("未传稿即收到完成码");return;}fileStarted=true;String owner=did;phase="file";deadline=SystemClock.elapsedRealtime()+60000;boolean accepted=NativeTransfer.sendOwned(did,did,text,1,0,60000,(state,result)->{if(!did.equals(owner)||phase.equals("closing")||phase.equals("uncertain"))return;if(state!=TransferGate.State.CONFIRMED){fail("新闻文件/收稿回执未齐全");return;}waiting=0;phase="ready";note="眼镜完整收稿，正在请求开始";control(3);});if(!accepted)fail("文件通道未接收稿件");}
   else if(code==7)NativeTransfer.ack(peer,1,0,0);return;}
  if(action==2&&e.type==waiting){if(code!=1){fail("眼镜拒绝控制（"+code+"）");return;}waiting=0;phase=e.type==4?"paused":"playing";note=e.type==4?"提词已暂停":"眼镜已确认匀速提词";}
  else if(action==1&&(e.type==3||e.type==4||e.type==5)){send(e.type,new JSONObject().put("did",did).put("action",2).put("code",1));phase=e.type==4?"paused":"playing";note=e.type==4?"眼镜已暂停":"眼镜继续阅读";}
 }catch(Exception e){fail("新闻回包格式不兼容");}}
}
