package com.turboio.addon;
import android.app.*;import android.os.*;import android.widget.*;import android.text.InputType;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.text.SimpleDateFormat;import java.util.*;
final class NewsUI {
 static void show(Activity a){EditorialUI.Screen s=new EditorialUI.Screen(a,"新闻阅读");LinearLayout b=s.body;android.content.SharedPreferences prefs=a.getSharedPreferences("turboio_news",0);EditText topic=input(a,b,"主题，例如 AI",prefs.getString("topic","AI"));TextView status=EditorialUI.text(a,"获取带来源的新闻摘要，稿件自动保存在本机。",14,EditorialUI.MUTED);b.addView(status);EditText body=input(a,b,"也可以粘贴自己的新闻稿","");body.setMinLines(5);body.setMaxLines(12);final boolean[] loading={false};EditText speed=input(a,b,"速度 60–1200",String.valueOf(prefs.getInt("speed",360)));speed.setInputType(InputType.TYPE_CLASS_NUMBER);
  EditorialUI.button(a,b,"获取新闻并保存",true,()->{if(loading[0])return;String q=topic.getText().toString().trim();if(q.isEmpty()||q.length()>80){status.setText("主题请输入1–80字");return;}loading[0]=true;status.setText("正在检索；只发送主题，不发送私人对话");prefs.edit().putString("topic",q).apply();new Thread(()->{String result=null;try{JSONObject data=new ToolClient(a.getApplicationContext()).call("web_search",new JSONObject().put("query",q+" 最新新闻 "+new SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).format(new Date())),SecretStore.get(a));JSONArray rows=data.getJSONArray("results");StringBuilder t=new StringBuilder(q+" · 新闻摘要\n"+new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.ROOT).format(new Date())+"\n\n");for(int i=0;i<rows.length();i++){JSONObject r=rows.getJSONObject(i);String entry=(i+1)+". "+r.optString("title")+"\n"+r.optString("snippet")+"\n来源："+r.optString("url")+"\n\n";if(t.length()+entry.length()>12000)break;t.append(entry);}if(rows.length()==0||t.indexOf("来源：")<0)throw new IOException();String candidate=t.toString();save(a,candidate);result=candidate;}catch(Exception ignored){}String answer=result;NativeTransfer.MAIN.post(()->{loading[0]=false;if(!s.dialog.isShowing())return;if(answer==null)status.setText("获取失败：检查设置里的联网搜索开关、TinyFish Key 和网络；未伪造新闻");else{body.setText(answer);status.setText("已保存在稿件库；这是搜索摘要，发布时间请以来源为准");}});},"TurboIO-news").start();});
  EditorialUI.button(a,b,"载入本机新闻稿",false,()->{File dir=new File(a.getFilesDir(),"news-library");File[] files=dir.listFiles(f->f.getName().matches("[0-9]+-[a-f0-9-]+\\.txt"));if(files==null||files.length==0){status.setText("暂无保存稿件");return;}Arrays.sort(files,Comparator.comparing(File::getName).reversed());String[] names=new String[files.length];for(int i=0;i<files.length;i++)names[i]=new SimpleDateFormat("MM-dd HH:mm:ss",Locale.ROOT).format(new Date(files[i].lastModified()));new AlertDialog.Builder(a).setTitle("本机稿件 · 退出不会删除").setItems(names,(d,w)->{try(InputStream in=new FileInputStream(files[w])){body.setText(ReaderCodec.utf8(BoundedHTTP.read(in,48000)));}catch(Exception e){status.setText("稿件读取失败");}}).show();});
  EditorialUI.button(a,b,"发送新闻并开始提词",true,()->{try{int n=Integer.parseInt(speed.getText().toString().trim());String content=body.getText().toString();if(n<60||n>1200||content.isEmpty()||content.length()>12000)throw new Exception();prefs.edit().putInt("speed",n).apply();EditorialUI.confirm(a,"开始新闻提词？","确认眼镜空闲。只准备本次稿件，无需在官方提词器先操作；超过360的速度仍需实机确认。",()->{try{save(a,content);NewsTele.start(content,n);}catch(Exception e){status.setText("稿件未保存，停止发送");}});}catch(Exception e){status.setText("检查稿件长度和速度（60–1200）");}});
  EditorialUI.button(a,b,"暂停",false,()->NewsTele.control(4));EditorialUI.button(a,b,"继续",false,()->NewsTele.control(5));EditorialUI.button(a,b,"退出眼镜提词",false,NewsTele::stop);EditorialUI.button(a,b,"已确认镜片退出，恢复通道",false,()->EditorialUI.confirm(a,"确认镜片已经回首页？","不会重发上次稿件。",NewsTele::reset));TextView transfer=EditorialUI.text(a,"",13,EditorialUI.LIME);b.addView(transfer);Handler h=new Handler();Runnable tick=new Runnable(){public void run(){if(!s.dialog.isShowing())return;transfer.setText(NewsTele.status()+"\n"+NativeTransfer.status());h.postDelayed(this,500);}};h.post(tick);s.dialog.setOnDismissListener(d->h.removeCallbacks(tick));}
 static EditText input(Activity a,LinearLayout b,String hint,String value){EditText e=new EditText(a);e.setTextColor(EditorialUI.INK);e.setHintTextColor(EditorialUI.MUTED);e.setTextSize(15);e.setHint(hint);e.setText(value);e.setBackground(EditorialUI.shape(a,EditorialUI.SURFACE,16));int p=EditorialUI.dp(a,12);e.setPadding(p,p,p,p);b.addView(e,new LinearLayout.LayoutParams(-1,-2));EditorialUI.gap(a,b,8);return e;}
 private static void save(Activity a,String text)throws IOException{byte[] bytes=text.getBytes(StandardCharsets.UTF_8);if(bytes.length>48000||text.length()>12000)throw new IOException();File dir=new File(a.getFilesDir(),"news-library");if(!dir.isDirectory()&&!dir.mkdirs())throw new IOException();File[] files=dir.listFiles();if(files==null||files.length>=100)throw new IOException("library full");ReaderLibrary.atomic(new File(dir,System.currentTimeMillis()+"-"+UUID.randomUUID()+".txt"),bytes);}
}
