package com.turboio.addon;
import android.content.*;import android.graphics.*;import org.json.*;import java.io.*;import java.nio.charset.*;import java.util.*;import java.util.concurrent.*;
final class ReaderLibrary {
 static void loadDemo()throws Exception{
  if(loading||webBusy||ReaderBridge.active())throw new IOException("请先结束当前阅读");
  for(int i=0;i<books.size();i++)if(books.get(i).id.equals("local-demo-7392")){first=i/4*4;note="内置测试书已在书架，未重复添加或覆盖正文";return;}
  if(books.size()>=1000)throw new IOException("书架已满");
  byte[] bytes;try(InputStream in=app.getAssets().open("turboio/reader/demo-7392.txt")){bytes=BoundedHTTP.read(in,32768);}
  ReaderCodec.wrap(ReaderCodec.utf8(bytes));ReaderCodec.Book b=new ReaderCodec.Book("local-demo-7392","Turbo IO 阅读测试 7392","原创 · 离线测试",books.size()+1);
  File file=contentFile(b);if(file.exists())throw new IOException("存在同名正文，未覆盖");
  atomic(file,bytes);books.add(b);try{save();}catch(Exception e){books.remove(b);file.delete();throw e;}
  first=(books.size()-1)/4*4;note="内置测试书已添加；无需 Key 或 Cookie，可发送书架后打开";
 }
 static Context app;static final List<ReaderCodec.Book> books=new ArrayList<>();static String note="同步书架或导入自己的 UTF-8 TXT";static int first,speed=240;static boolean automatic,loading;static ReaderCodec.Book selected;static List<String> lines=Collections.emptyList();private static final ExecutorService IO=Executors.newSingleThreadExecutor();private static long generation;private static boolean webBusy;
 static void init(Context c){if(app!=null)return;app=c.getApplicationContext();speed=app.getSharedPreferences("turboio_reader",0).getInt("speed",240);ReaderBridge.init(app,ReaderLibrary::event);BackgroundWork.register("阅读",ReaderLibrary::stop);try{File f=new File(app.getFilesDir(),"reader-shelf.json");if(f.isFile())try(InputStream in=new FileInputStream(f)){parse(new JSONArray(ReaderCodec.utf8(BoundedHTTP.read(in,2*1024*1024))));}}catch(Exception ignored){}}
 private static void parse(JSONArray rows)throws Exception{if(rows==null||rows.length()>1000)throw new IOException("书架超过1000本，请缩小范围");List<ReaderCodec.Book> temp=new ArrayList<>();Set<String> ids=new HashSet<>();for(int i=0;i<Math.min(rows.length(),1000);i++){JSONObject j=rows.optJSONObject(i);if(j==null)continue;JSONObject info=j.optJSONObject("bookInfo");if(info!=null)j=info;String id=j.optString("bookId",j.optString("id",""));if(id.isEmpty()||id.length()>128||!ids.add(id))continue;ReaderCodec.Book b=new ReaderCodec.Book(id,j.optString("title",j.optString("name","未命名")),j.optString("author"),temp.size()+1);b.coverURL=j.optString("cover",j.optString("coverURL",""));temp.add(b);}books.clear();books.addAll(temp);}
 static void save()throws Exception{JSONArray j=new JSONArray();for(ReaderCodec.Book b:books)j.put(new JSONObject().put("bookId",b.id).put("title",b.title).put("author",b.author).put("cover",b.coverURL==null?"":b.coverURL));byte[] bytes=j.toString().getBytes(StandardCharsets.UTF_8);if(bytes.length>2*1024*1024)throw new IOException("书架数据过大");atomic(new File(app.getFilesDir(),"reader-shelf.json"),bytes);}
 static void atomic(File f,byte[] b)throws IOException{android.util.AtomicFile a=new android.util.AtomicFile(f);FileOutputStream out=null;try{out=a.startWrite();out.write(b);a.finishWrite(out);}catch(IOException e){if(out!=null)a.failWrite(out);throw e;}}
 static void sync(Runnable changed){if(loading||ReaderBridge.active()){note="正在同步或眼镜阅读中，请先退出";changed.run();return;}loading=true;note="正在获取书架";IO.execute(()->{JSONArray rows=null;String error=null;try{String key=SecretStore.get(app,"weread_key");if(key.isEmpty())throw new IOException("请先设置书架 Key");JSONObject j=new JSONObject(ReaderCodec.utf8(BoundedHTTP.request("https://i.weread.qq.com/api/agent/gateway",Collections.singletonMap("Authorization","Bearer "+key),new JSONObject().put("api_name","/shelf/sync").put("skill_version","1.0.4").toString(),4*1024*1024)));if(j.has("upgrade_info")||j.optInt("errcode",0)!=0)throw new IOException("鉴权失败或服务要求升级 Skill");JSONObject d=j.optJSONObject("data");if(d==null)d=j;rows=d.optJSONArray("books");if(rows==null)throw new IOException("书架结构不兼容");}catch(Exception e){error="书架获取失败：检查 Key、联网或服务版本";}JSONArray result=rows;String fail=error;NativeTransfer.MAIN.post(()->{loading=false;try{if(fail!=null){note=fail;}else{List<ReaderCodec.Book> local=new ArrayList<>();for(ReaderCodec.Book old:books)if(old.id.startsWith("local-"))local.add(old);if(result.length()+local.size()>1000)throw new IOException("书架超出上限");List<ReaderCodec.Book> previous=new ArrayList<>(books);try{parse(result);for(ReaderCodec.Book old:local){ReaderCodec.Book copy=new ReaderCodec.Book(old.id,old.title,old.author,books.size()+1);copy.coverURL=old.coverURL;books.add(copy);}save();}catch(Exception e){books.clear();books.addAll(previous);throw e;}first=0;note="已保存 "+books.size()+" 本书；书架 Key 不提供正文";}}catch(Exception e){note="书架保存失败或超过1000本/2MiB上限；原书架保留";}changed.run();});});}
 static void send(int page){if(loading)return;if(page<0||page>books.size()||page%4!=0)return;cancelWeb();first=page;loading=true;long epoch=++generation;note="处理本页封面（64×88）";List<ReaderCodec.Book> all=new ArrayList<>();for(ReaderCodec.Book original:books){ReaderCodec.Book copy=new ReaderCodec.Book(original.id,original.title,original.author,original.token);copy.coverURL=original.coverURL;all.add(copy);}IO.execute(()->{for(ReaderCodec.Book b:all){b.cover=null;}int missing=0;for(int i=page;i<Math.min(page+4,all.size());i++){ReaderCodec.Book b=all.get(i);try{URLCheck(b.coverURL);byte[] data=coverFetch(b.coverURL);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(data,0,data.length,o);if(o.outWidth<=0||o.outHeight<=0||(long)o.outWidth*o.outHeight>40000000)throw new IOException();o.inJustDecodeBounds=false;while(Math.max(o.outWidth,o.outHeight)/Math.max(1,o.inSampleSize)>512)o.inSampleSize=o.inSampleSize<1?2:o.inSampleSize*2;Bitmap raw=BitmapFactory.decodeByteArray(data,0,data.length,o);if(raw==null)throw new IOException();Bitmap small=Bitmap.createScaledBitmap(raw,64,88,true);int[] px=new int[5632];small.getPixels(px,0,64,0,0,64,88);byte[] cover=new byte[5632];for(int p=0;p<px.length;p++)cover[p]=(byte)((Color.red(px[p])*54+Color.green(px[p])*183+Color.blue(px[p])*19)>>8);b.cover=cover;if(small!=raw)raw.recycle();small.recycle();}catch(Exception ignored){missing++;b.cover=placeholder();}}byte[] payload=ReaderCodec.shelf(all,page);final int absent=missing;NativeTransfer.MAIN.post(()->{if(epoch!=generation)return;loading=false;note=absent==0?"本页封面处理完成；等待眼镜确认":"本页"+absent+"张封面未获取，已用占位图；等待眼镜确认";ReaderBridge.open(payload);});});}
 static void URLCheck(String s)throws Exception{java.net.URI u=new java.net.URI(s==null?"":s);if(!"https".equals(u.getScheme())||!Arrays.asList("cdn.weread.qq.com","res.weread.qq.com","weread-1258476243.file.myqcloud.com","wrco-40036.sh.gfp.tencent-cloud.com").contains(u.getHost()))throw new IOException();}
 private static byte[] coverFetch(String url)throws Exception{for(int hop=0;hop<4;hop++){URLCheck(url);java.net.URL u=new java.net.URL(url);if(u.getUserInfo()!=null||u.getRef()!=null||u.getPort()!=-1&&u.getPort()!=443)throw new IOException();java.net.HttpURLConnection c=(java.net.HttpURLConnection)u.openConnection();try{c.setInstanceFollowRedirects(false);c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setUseCaches(false);int code=c.getResponseCode();if(code>=300&&code<400){String location=c.getHeaderField("Location");if(location==null)throw new IOException();url=u.toURI().resolve(location).toString();continue;}if(code!=200||c.getContentLengthLong()>8*1024*1024)throw new IOException();try(InputStream in=c.getInputStream()){return BoundedHTTP.read(in,8*1024*1024);}}finally{c.disconnect();}}throw new IOException("redirect limit");}
 static void statistics(String mode,java.util.function.Consumer<String> result){if(!Arrays.asList("weekly","monthly","annually","overall").contains(mode))return;if(loading||webBusy){result.accept("请等待当前读取完成");return;}loading=true;IO.execute(()->{String message;try{String key=SecretStore.get(app,"weread_key");if(key.isEmpty())throw new IOException();JSONObject j=new JSONObject(ReaderCodec.utf8(BoundedHTTP.request("https://i.weread.qq.com/api/agent/gateway",Collections.singletonMap("Authorization","Bearer "+key),new JSONObject().put("api_name","/readdata/detail").put("skill_version","1.0.4").put("mode",mode).put("baseTime",0).toString(),4*1024*1024)));if(j.has("upgrade_info")||j.optInt("errcode",0)!=0)throw new IOException();JSONObject d=j.optJSONObject("data");if(d==null)d=j;StringBuilder out=new StringBuilder("阅读时长："+duration(d.opt("totalReadTime"))+"\n阅读天数："+(d.opt("readDays") instanceof Number?d.optLong("readDays")+"天":"暂无数据")+"\n自然日均："+duration(d.opt("dayAverageReadTime"))+"\n\n偏好（服务端时长）\n");JSONArray rows=d.optJSONArray("preferCategory");List<JSONObject> categories=new ArrayList<>();if(rows!=null&&rows.length()<=256)for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(r!=null&&r.optDouble("readingTime")>0)categories.add(r);}categories.sort((x,y)->Double.compare(y.optDouble("readingTime"),x.optDouble("readingTime")));for(int i=0;i<Math.min(8,categories.size());i++){JSONObject r=categories.get(i);out.append(r.optString("categoryTitle")).append("：").append(duration(r.opt("readingTime"))).append('\n');}out.append("\n投入参考，不等于理解深度；时长包含阅读与收听，不把缺失值当作0。");message=out.toString();}catch(Exception e){message="阅读统计不可用，请检查书架 Key、网络或服务版本";}String value=message;NativeTransfer.MAIN.post(()->{loading=false;result.accept(value);});});}
 private static String duration(Object value){if(!(value instanceof Number))return "暂无数据";double n=((Number)value).doubleValue();if(!Double.isFinite(n)||n<0||n>1e12)return "暂无数据";long s=(long)n;return s>0&&s<60?"不足1分钟":s/3600+"小时"+s%3600/60+"分钟";}
 private static byte[] placeholder(){byte[] p=new byte[5632];for(int y=6;y<82;y++)for(int x=6;x<58;x++)if(x<9||x>54||y<9||y>78)p[y*64+x]=(byte)180;return p;}
 static void importText(byte[] data,ReaderCodec.Book book)throws Exception{if(loading||webBusy||ReaderBridge.active())throw new IOException("请先结束阅读");String s=ReaderCodec.utf8(data);ReaderCodec.wrap(s);ReaderCodec.Book b=book;if(b==null){if(books.size()>=1000)throw new IOException("书架已满");b=new ReaderCodec.Book("local-"+UUID.randomUUID(),"导入的本机书籍","本机 TXT",books.size()+1);books.add(b);}atomic(contentFile(b),data);save();note="正文已保存，可选中发送";}
 private static File contentFile(ReaderCodec.Book b){return new File(app.getFilesDir(),"reader-"+UUID.nameUUIDFromBytes(b.id.getBytes(StandardCharsets.UTF_8))+".txt");}
 static void read(ReaderCodec.Book b,int row){
  if(loading)return;
  try{
   File file=contentFile(b);
   if(!file.isFile()){note="公开版不含网页正文适配，请先导入有权使用的对应 TXT";return;}
   if(selected==null||!selected.id.equals(b.id))lines=Collections.emptyList();
   selected=b;
   if(lines.isEmpty())try(InputStream in=new FileInputStream(file)){lines=ReaderCodec.wrap(ReaderCodec.utf8(BoundedHTTP.read(in,2*1024*1024)));}
   ReaderBridge.open(ReaderCodec.window(b,lines,Math.min(row,lines.size()-1),speed,automatic));
   note="正在发送本地正文窗口";
  }catch(Exception e){note="正文格式或限额无效，请导入 UTF-8 TXT";}
 }
 static void cancelWeb(){generation++;webBusy=false;lines=Collections.emptyList();}
 static void stop(){cancelWeb();loading=false;ReaderBridge.close();}
 private static void event(ReaderCodec.Reply r){if(r.event==1){cancelWeb();if(r.sid==0){note="眼镜请求书架；请在手机点击发送确认本次阅读";return;}send((int)r.value);}else if(r.event==2){for(ReaderCodec.Book b:books)if(b.token==r.value){lines=Collections.emptyList();read(b,0);break;}}else if(r.event==3&&selected!=null&&r.token==selected.token){automatic=r.automatic;speed=r.speed>=30&&r.speed<=480?r.speed:speed;read(selected,(int)r.value);}else if(r.event==4)cancelWeb();}
}
