package com.turboio.addon;
import android.app.*;import android.os.*;import android.text.InputType;import android.widget.*;
final class ReaderUI {
 static void probeButton(Activity a,LinearLayout b){EditorialUI.button(a,b,"只读检查眼镜入口状态",false,()->{EntryProbe.query();new Handler().postDelayed(()->{if(!a.isFinishing())EditorialUI.notice(a,EntryProbe.status());},5500);});}
 static void show(Activity a){EditorialUI.Screen s=new EditorialUI.Screen(a,"微信读书");LinearLayout b=s.body;TextView status=EditorialUI.text(a,"",14,EditorialUI.LIME);b.addView(status);b.addView(EditorialUI.text(a,"四本书架 · 手机处理封面 · 眼镜有界阅读\n书架 Key 只读取书架。公开版仅支持导入 UTF-8 TXT 正文；网页正文适配未包含。",14,EditorialUI.MUTED));
  probeButton(a,b);
  LinearLayout list=EditorialUI.column(a);Runnable render=()->{list.removeAllViews();for(int i=ReaderLibrary.first;i<Math.min(ReaderLibrary.first+4,ReaderLibrary.books.size());i++){ReaderCodec.Book book=ReaderLibrary.books.get(i);EditorialUI.button(a,list,book.title+"\n"+book.author,false,()->new AlertDialog.Builder(a).setTitle(book.title).setItems(new String[]{"打开正文并发送","导入对应 TXT 正文"},(d,w)->{if(w==0)ReaderLibrary.read(book,0);else DocumentPicker.pick(a,2*1024*1024,bytes->{try{ReaderLibrary.importText(bytes,book);}catch(Exception e){EditorialUI.notice(a,"不是有效 UTF-8 正文或超过限额");}});}).show());}};
  EditorialUI.button(a,b,"载入内置测试书 · 7392（无需账号）",false,()->{try{ReaderLibrary.loadDemo();render.run();}catch(Exception e){EditorialUI.notice(a,e.getMessage()==null?"载入失败，原书架保留":e.getMessage());}});
  EditorialUI.button(a,b,"配置书架 Key",false,()->{EditText key=new EditText(a);key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);key.setHint("留空不修改；不展示已有凭据");new AlertDialog.Builder(a).setTitle("本机加密保存").setView(key).setNegativeButton("取消",null).setNeutralButton("清除",(d,w)->{try{SecretStore.put(a,"weread_key","");}catch(Exception e){EditorialUI.notice(a,"清除失败");}}).setPositiveButton("保存",(d,w)->{String k=key.getText().toString().trim();if(!k.isEmpty())try{if(!k.startsWith("wrk-")||k.length()>256||k.matches(".*\\s.*"))throw new Exception();SecretStore.put(a,"weread_key",k);}catch(Exception e){EditorialUI.notice(a,"Key 格式无效或保存失败");}}).show();});
  EditorialUI.button(a,b,"阅读时长与偏好",false,()->new AlertDialog.Builder(a).setTitle("统计范围").setItems(new String[]{"本周","本月","本年","累计"},(d,w)->ReaderLibrary.statistics(new String[]{"weekly","monthly","annually","overall"}[w],v->{if(s.dialog.isShowing())EditorialUI.notice(a,v);})).show());EditorialUI.button(a,b,"同步微信读书书架",false,()->ReaderLibrary.sync(render));EditorialUI.button(a,b,"发送四本书架到眼镜",true,()->EditorialUI.confirm(a,"发送当前书架？","请确认眼镜空闲；仅发送当前四本，翻页替换旧页。",()->ReaderLibrary.send(ReaderLibrary.first)));b.addView(list);EditorialUI.button(a,b,"上一页",false,()->{ReaderLibrary.first=Math.max(0,ReaderLibrary.first-4);render.run();});EditorialUI.button(a,b,"下一页",false,()->{if(ReaderLibrary.first+4<ReaderLibrary.books.size())ReaderLibrary.first+=4;render.run();});EditorialUI.button(a,b,"新增本机 TXT",false,()->DocumentPicker.pick(a,2*1024*1024,bytes->{try{ReaderLibrary.importText(bytes,null);render.run();}catch(Exception e){EditorialUI.notice(a,"导入失败：仅接受不超过50万字符的 UTF-8 TXT");}}));EditorialUI.toggle(a,b,"新正文窗口自动滚动",ReaderLibrary.automatic,(v,on)->ReaderLibrary.automatic=on);EditorialUI.button(a,b,"阅读速度（30–480字/分钟）",false,()->{EditText value=new EditText(a);value.setInputType(InputType.TYPE_CLASS_NUMBER);value.setText(""+ReaderLibrary.speed);new AlertDialog.Builder(a).setView(value).setPositiveButton("保存",(d,w)->{try{int n=Integer.parseInt(value.getText().toString());if(n<30||n>480)throw new Exception();ReaderLibrary.speed=n;a.getSharedPreferences("turboio_reader",0).edit().putInt("speed",n).apply();}catch(Exception e){EditorialUI.notice(a,"请输入30–480");}}).setNegativeButton("取消",null).show();});EditorialUI.button(a,b,"退出眼镜阅读",false,ReaderLibrary::stop);EditorialUI.button(a,b,"已确认眼镜回首页，恢复同步",false,()->EditorialUI.confirm(a,"确认镜片已退出？","不自动重发上次未知结果的命令。",ReaderBridge::reset));render.run();Handler h=new Handler();Runnable tick=new Runnable(){public void run(){if(!s.dialog.isShowing())return;status.setText(ReaderLibrary.note+"\n"+ReaderBridge.status());h.postDelayed(this,500);}};h.post(tick);s.dialog.setOnDismissListener(d->h.removeCallbacks(tick));}
}
