#ifndef TIO_IMAGE_WIRE_FORMAT_H
#define TIO_IMAGE_WIRE_FORMAT_H
#ifndef TIO_IMAGE_RX_WIDE
#define TIO_IMAGE_RX_WIDE 0
#endif
#if TIO_IMAGE_RX_WIDE
enum {TIO_W=512,TIO_H=128,TIO_VERSION=2};
#else
enum {TIO_W=128,TIO_H=64,TIO_VERSION=1};
#endif
enum {TIO_PIXELS=TIO_W*TIO_H,TIO_HEADER=32,TIO_WIRE=TIO_PIXELS+TIO_HEADER};
#define TIO_WIRE_PREFIX {'T','I','M','G',TIO_VERSION,1,32,0, \
 (TIO_W&255),(TIO_W>>8),(TIO_H&255),(TIO_H>>8),(TIO_W&255),(TIO_W>>8),0,0, \
 (TIO_PIXELS&255),((TIO_PIXELS>>8)&255),((TIO_PIXELS>>16)&255),((TIO_PIXELS>>24)&255)}
#endif
