#import "KnowledgeUI.h"
#import "KnowledgeClient.h"
#import "ResearchUI.h"
UIButton *TIOAgentPicker(void (^changed)(void)){
    UIButton *b=[UIButton buttonWithType:UIButtonTypeSystem];b.showsMenuAsPrimaryAction=YES;UIButtonConfiguration *c=UIButtonConfiguration.tintedButtonConfiguration;c.title=TIOSelectedAgent();c.image=[UIImage systemImageNamed:@"chevron.down"];c.imagePlacement=NSDirectionalRectEdgeTrailing;c.imagePadding=6;c.cornerStyle=UIButtonConfigurationCornerStyleCapsule;b.configuration=c;
    NSMutableArray *actions=[NSMutableArray new];for(NSString *name in @[@"Codex",@"Claude Code",@"Hermes",@"WorkBuddy",@"OpenClaw"]){UIAction *a=[UIAction actionWithTitle:name image:nil identifier:nil handler:^(UIAction *action){[[[NSUserDefaults alloc]initWithSuiteName:@"io.turboio.official-knowledge"] setObject:name forKey:@"agent"];if(changed)changed();}];a.state=[TIOSelectedAgent() isEqual:name]?UIMenuElementStateOn:UIMenuElementStateOff;[actions addObject:a];}b.menu=[UIMenu menuWithTitle:@"选择 Agent" children:actions];[b sizeToFit];return b;
}
@interface TIOKnowledgePanel:UITableViewController
@property(nonatomic) TIOKnowledgeClient *client;
@property(nonatomic) NSDictionary *sources,*job;
@property(nonatomic) NSString *status;
@end
@implementation TIOKnowledgePanel
- (void)viewDidLoad{[super viewDidLoad];self.title=@"知识库";TIOStyleResearchTable(self);self.job=TIOKnowledgeSnapshot();self.status=@"projectmanager · 只读查询";self.tableView.tableHeaderView=TIOFeatureHeader(@"连接你的知识",@"从眼镜提问，让 Agent 查证来源。",@"reading");[self refreshSources];}
- (void)dealloc{[self.client cancel];}
- (void)viewDidDisappear:(BOOL)animated{[super viewDidDisappear:animated];if(!self.navigationController||!self.view.window)[self.client cancel];}
- (void)alert:(NSString *)text{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"知识库" message:text preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"知道了" style:UIAlertActionStyleCancel handler:nil]];[self presentViewController:a animated:YES completion:nil];}
- (NSInteger)numberOfSectionsInTableView:(UITableView *)t{return 4;}
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s{return s==0?4:s==1?[self.sources[@"sources"] count]:s==2?2:MAX(1,[self.job[@"results"] count]);}
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s{return @[@"连接与权限",@"数据来源",@"查询与结果",@"本次引用来源"][s];}
- (NSString *)tableView:(UITableView *)t titleForFooterInSection:(NSInteger)s{if(s==0)return @"仅 Codex 已接执行器；其他 Agent 可选择但尚未连接。令牌存手机钥匙串。";if(s==1)return @"只查询 Mac 已归档数据，不刷新微信、不读实时数据库。命中片段经 Codex 处理，答案会交给当前自有模型。";if(s==2)return @"长查询保留在 Mac；刷新结果可继续查看。本版未接 APNs，退出后不保证主动通知。";return nil;}
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)ip{
    UITableViewCell *c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil];TIOStyleResearchCell(c);c.textLabel.numberOfLines=0;c.detailTextLabel.numberOfLines=0;c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;
    if(ip.section==0){c.textLabel.text=@[@"知识库工具",@"执行 Agent",@"连接配置",@"刷新连接状态"][ip.row];if(ip.row==0){UISwitch *s=[UISwitch new];s.on=TIOKnowledgeEnabled();[s addTarget:self action:@selector(toggle:) forControlEvents:UIControlEventValueChanged];c.accessoryView=s;c.detailTextLabel.text=@"允许语音调用只读知识库";}if(ip.row==1){__weak typeof(self) weak=self;c.accessoryView=TIOAgentPicker(^{[weak.tableView reloadData];});c.detailTextLabel.text=[TIOSelectedAgent() isEqual:@"Codex"]?@"Codex App Server · Mac 执行":@"未连接执行器";}if(ip.row==2)c.detailTextLabel.text=TIOKnowledgeEndpoint().length?TIOKnowledgeEndpoint():@"设置 HTTPS 地址与专用令牌";if(ip.row==3)c.detailTextLabel.text=self.status;}
    else if(ip.section==1){NSDictionary *s=self.sources[@"sources"][ip.row];c.textLabel.text=s[@"name"];c.detailTextLabel.text=[NSString stringWithFormat:@"%@ · %@ 条\n更新时间：%@\n%@%@",[s[@"available"] boolValue]?@"可读取":@"不可用",s[@"count"]?:@0,s[@"updatedAt"]?:@"未知",s[@"scope"]?:@"",[s[@"partial"] boolValue]?@"\n存在范围限制或跳过文件":@""];c.accessoryType=UITableViewCellAccessoryNone;}
    else if(ip.section==2){c.textLabel.text=ip.row==0?@"发起查询":@"刷新最近结果";c.detailTextLabel.text=ip.row==0?@"例如：微信中某项目最近有什么进展？":[NSString stringWithFormat:@"%@\n%@",self.job[@"status"]?:@"尚无查询",self.job[@"answer"]?:self.job[@"error"]?:@""];}
    else {NSArray *r=self.job[@"results"];if(!r.count){c.textLabel.text=@"暂无引用";c.detailTextLabel.text=@"完成查询后显示实际来源。";}else{NSDictionary *e=r[ip.row];c.textLabel.text=e[@"title"];c.detailTextLabel.text=[NSString stringWithFormat:@"%@ · %@\n%@",e[@"sourceLabel"]?:@"",e[@"messageAt"]==NSNull.null?e[@"updatedAt"]:e[@"messageAt"]?:e[@"updatedAt"],e[@"excerpt"]?:@""];}c.accessoryType=UITableViewCellAccessoryNone;}return c;
}
- (void)toggle:(UISwitch *)s{TIOSetKnowledgeEnabled(s.on);if(s.on&&!TIOKnowledgeEnabled()){s.on=NO;[self alert:@"请先配置连接，并选择 Codex。"];}}
- (void)refreshSources{[self.client cancel];self.client=[TIOKnowledgeClient new];self.status=@"连接中…";__weak typeof(self) weak=self;[self.client sources:^(NSDictionary *j,NSString *e){weak.sources=j;weak.status=e?:@"Mac 服务已连接 · Codex 按查询启动";[weak.tableView reloadData];}];}
- (void)configure{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"知识库连接" message:@"私有 HTTPS 网关。令牌不回显，留空保留。" preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField *f){f.text=TIOKnowledgeEndpoint();f.placeholder=@"https://…/api/turbo-knowledge";f.autocapitalizationType=UITextAutocapitalizationTypeNone;}];[a addTextFieldWithConfigurationHandler:^(UITextField *f){f.placeholder=@"专用连接令牌";f.secureTextEntry=YES;}];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"保存" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){BOOL ok=TIOConfigureKnowledge(a.textFields[0].text,a.textFields[1].text);a.textFields[1].text=@"";if(ok)[self refreshSources];else [self alert:@"地址或令牌无效，未保存。"]; }]];[self presentViewController:a animated:YES completion:nil];}
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)ip{[t deselectRowAtIndexPath:ip animated:YES];if(ip.section==0){if(ip.row==2)[self configure];if(ip.row==3)[self refreshSources];return;}if(ip.section!=2)return;
    if(ip.row==1){[self.client cancel];self.client=[TIOKnowledgeClient new];__weak typeof(self) weak=self;[self.client refreshLast:^(NSDictionary *j,NSString *e){if(j)weak.job=j;if(e)[weak alert:e];[weak.tableView reloadData];}];return;}
    UIAlertController *a=[UIAlertController alertControllerWithTitle:@"让 Codex 查知识库" message:@"仅检索已归档资料，不执行写入。" preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField *f){f.placeholder=@"输入想查询的问题";}];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"查询" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){NSString *q=a.textFields[0].text?:@"";if(q.length<2||q.length>200){[self alert:@"请输入2至200字。"];return;}[self.client cancel];self.client=[TIOKnowledgeClient new];self.job=@{@"status":@"查询中…"};[self.tableView reloadData];__weak typeof(self) weak=self;[self.client query:@{@"query":q,@"source":@"all"} completion:^(NSDictionary *j,NSString *e){if(j)weak.job=j;if(e)[weak alert:e];[weak.tableView reloadData];}];}]];[self presentViewController:a animated:YES completion:nil];
}
@end
void TIOOpenKnowledge(UIViewController *host){[host.navigationController pushViewController:[[TIOKnowledgePanel alloc]initWithStyle:UITableViewStyleInsetGrouped] animated:YES];}
