#import <UIKit/UIKit.h>
#import "ResearchUI.h"
#import <objc/runtime.h>
#import "RecordingExports.h"
@interface TIORecordingExportsPanel:UITableViewController<UIDocumentPickerDelegate>
@property(nonatomic) NSArray<NSDictionary *> *audio;
@property(nonatomic) BOOL busy;
@end
@implementation TIORecordingExportsPanel
- (void)viewDidLoad{[super viewDidLoad];self.title=@"录音与文本分享";TIOStyleResearchTable(self);self.tableView.tableHeaderView=TIOFeatureHeader(@"留住这一刻",@"声音与文字，保存到自己的文件。",@"music");self.navigationItem.rightBarButtonItem=[[UIBarButtonItem alloc]initWithBarButtonSystemItem:UIBarButtonSystemItemRefresh target:self action:@selector(refresh)];[self refresh];}
- (void)refresh{if(self.busy)return;self.busy=YES;dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{NSArray *rows=TIOPreparedAudioFiles([NSURL fileURLWithPath:NSHomeDirectory()]);dispatch_async(dispatch_get_main_queue(),^{self.audio=rows;self.busy=NO;[self.tableView reloadData];});});}
- (NSInteger)numberOfSectionsInTableView:(UITableView *)t{return 2;}
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s{return s==0?MAX(1,self.audio.count):1;}
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s{return s==0?@"本机已准备的音频":@"Markdown 文本";}
- (NSString *)tableView:(UITableView *)t titleForFooterInSection:(NSInteger)s{return s==0?@"先在官方录音详情：分享 → 音频，生成所需格式。这里列出已生成的文件，不自动对应当前详情；请核对名称和时间。点击后分享独立副本，可选 AirDrop 或存储到文件。不会生成公开链接，不删原录音。":@"当前详情的全量转写读取尚未接通。可先导入已有完整 TXT/MD 文件生成 Markdown；不会把屏幕上可见的几段当作全文。";}
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)ip{UITableViewCell *c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil];TIOStyleResearchCell(c);c.detailTextLabel.numberOfLines=0;if(ip.section==1){c.textLabel.text=@"导入 TXT / MD 并分享 Markdown";c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;}else if(!self.audio.count){c.textLabel.text=self.busy?@"正在读取本机文件…":@"暂无已准备音频";c.selectionStyle=UITableViewCellSelectionStyleNone;}else{NSDictionary *row=self.audio[ip.row];c.textLabel.text=row[@"name"];c.textLabel.numberOfLines=2;NSDateFormatter *fmt=[NSDateFormatter new];fmt.dateFormat=@"MM-dd HH:mm";c.detailTextLabel.text=[NSString stringWithFormat:@"%@ · %@",[fmt stringFromDate:row[@"date"]],[NSByteCountFormatter stringFromByteCount:[row[@"bytes"] longLongValue] countStyle:NSByteCountFormatterCountStyleFile]];c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;}return c;}
- (void)showError:(NSString *)message{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"未分享" message:message preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"知道了" style:UIAlertActionStyleCancel handler:nil]];[self presentViewController:a animated:YES completion:nil];}
- (void)share:(NSURL *)file{UIActivityViewController *sheet=[[UIActivityViewController alloc]initWithActivityItems:@[file] applicationActivities:nil];sheet.popoverPresentationController.sourceView=self.view;sheet.popoverPresentationController.sourceRect=CGRectMake(self.view.bounds.size.width/2,100,1,1);[self presentViewController:sheet animated:YES completion:nil];}
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)ip{[t deselectRowAtIndexPath:ip animated:YES];if(self.busy)return;if(ip.section==1){UIDocumentPickerViewController *p=[[UIDocumentPickerViewController alloc]initWithDocumentTypes:@[@"public.plain-text",@"net.daringfireball.markdown"] inMode:UIDocumentPickerModeImport];p.delegate=self;p.allowsMultipleSelection=NO;[self presentViewController:p animated:YES completion:nil];return;}if(ip.row>=self.audio.count)return;NSURL *source=self.audio[ip.row][@"url"];self.busy=YES;dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{NSError *error=nil;NSURL *file=TIOAudioShareCopy([NSURL fileURLWithPath:NSHomeDirectory()],source,&error);dispatch_async(dispatch_get_main_queue(),^{self.busy=NO;if(file)[self share:file];else [self showError:error.localizedDescription];});});}
- (void)documentPicker:(UIDocumentPickerViewController *)p didPickDocumentsAtURLs:(NSArray<NSURL *> *)urls{NSURL *url=urls.firstObject;if(!url)return;self.busy=YES;dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{NSError *error=nil;NSNumber *size=nil;[url getResourceValue:&size forKey:NSURLFileSizeKey error:&error];NSString *text=nil;if(size&&size.unsignedLongLongValue<=8*1024*1024)text=[NSString stringWithContentsOfURL:url encoding:NSUTF8StringEncoding error:&error];NSURL *file=text?TIOMarkdownShareFile([NSURL fileURLWithPath:NSHomeDirectory()],url.lastPathComponent.stringByDeletingPathExtension,text,&error):nil;dispatch_async(dispatch_get_main_queue(),^{self.busy=NO;if(file){if(self.presentedViewController)[self dismissViewControllerAnimated:YES completion:^{[self share:file];}];else [self share:file];}else [self showError:@"只支持完整的 UTF-8 文本文件（不超过 8 MB / 200 万字符）。未读取官方历史全文。"];});});}
@end
