package com.turboio.addon;
import java.lang.reflect.*;import java.util.*;import android.os.SystemClock;
public class ReaderFlowTest {
 static int n,events;static void ok(boolean b){n++;if(!b)throw new AssertionError(n+": "+ReaderBridge.status());}
 static void pump()throws Exception{SystemClock.now+=150;Method m=ReaderBridge.class.getDeclaredMethod("pump");m.setAccessible(true);m.invoke(null);}
 static byte[] envelope(byte[] b){StringBuilder h=new StringBuilder();for(byte v:b)h.append(String.format("%02x",v&255));byte[] j=("{\"cmd\":\"turbo_read_v1\",\"payload\":{\"data\":\""+h+"\"}}").getBytes(java.nio.charset.StandardCharsets.UTF_8);java.io.ByteArrayOutputStream o=new java.io.ByteArrayOutputStream();o.write(8);o.write(1);o.write(16);o.write(6);o.write(26);int len=j.length;while(len>=128){o.write((len&127)|128);len>>>=7;}o.write(len);o.write(j,0,j.length);return o.toByteArray();}
 static void reply(String peer,int event,int result,long sequence,long id){byte[] b=new byte[48];System.arraycopy(new byte[]{87,82,65,49,1,(byte)event,(byte)result,1},0,b,0,8);ReaderCodec.put(b,8,NativeTransfer.session);ReaderCodec.put(b,12,sequence);ReaderCodec.put(b,20,id);ReaderCodec.put(b,24,result==3?4:0);ReaderCodec.put(b,44,ReaderCodec.crc(Arrays.copyOf(b,44)));NativeTransfer.receiver.message(peer,envelope(b));if(peer.equals("glasses")&&event==0&&result==3&&sequence==NativeTransfer.request){ok(ReaderBridge.status().contains("入口原因 4"));ok(ReaderBridge.status().contains("其他显示页面占用"));}}
 public static void main(String[] args)throws Exception{ReaderBridge.init(new android.content.Context(),r->events++);byte[] page=ReaderCodec.shelf(Collections.emptyList(),0);ReaderBridge.open(page);ok(ReaderBridge.active()&&NativeTransfer.sent[5]==1);int count=NativeTransfer.sends;ReaderBridge.open(page);ok(NativeTransfer.sends==count);reply("other",0,0,NativeTransfer.request,0);ok(NativeTransfer.busy);reply("glasses",0,0,NativeTransfer.request+1,0);ok(NativeTransfer.busy);reply("glasses",0,0,NativeTransfer.request,0);pump();ok(NativeTransfer.sent[5]==2);reply("glasses",0,0,NativeTransfer.request,0);pump();ok(NativeTransfer.sent[5]==3);ok(ReaderCodec.get(NativeTransfer.sent,20)==0);reply("glasses",0,0,NativeTransfer.request,0);pump();ok(NativeTransfer.sent[5]==4);reply("glasses",0,0,NativeTransfer.request,0);ok(!ReaderBridge.busy());reply("glasses",1,0,NativeTransfer.request,100);ok(events==1);reply("glasses",1,0,NativeTransfer.request,100);ok(events==1);ReaderBridge.close();pump();ok(NativeTransfer.sent[5]==6);reply("glasses",0,0,NativeTransfer.request,0);ok(!ReaderBridge.active());ReaderBridge.open(page);NativeTransfer.complete(TransferGate.State.UNCERTAIN,0);ok(!ReaderBridge.active());count=NativeTransfer.sends;ReaderBridge.open(page);ok(NativeTransfer.sends==count);ReaderBridge.reset();ReaderBridge.open(page);reply("glasses",0,3,NativeTransfer.request,0);ok(!ReaderBridge.active());count=NativeTransfer.sends;ReaderBridge.open(page);ok(ReaderBridge.active()&&NativeTransfer.sends==count+1);reply("glasses",0,0,NativeTransfer.request,0);NativeTransfer.peer="changed";pump();ok(!ReaderBridge.active());System.out.println("ReaderFlow: "+n+" checks (mock transport)");}
}
