#import "AppUI.h"
#import "AppBridge.h"
#import "AppPackage.h"
#import "ResearchUI.h"
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>
static void Notice(UIViewController *v,NSString *s){UIAlertController *a=[UIAlertController alertControllerWithTitle:@"我的应用 · 开发者预览" message:s preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"知道了" style:UIAlertActionStyleCancel handler:nil]];[v presentViewController:a animated:YES completion:nil];}
static NSArray<NSDictionary *> *Builtins(void){return @[
 @{@"resource":@"TurboAppSDKExample",@"name":@"每日简报",@"detail":@"2 页 · 入门交互 · 已安装的同版本无需重装"},
 @{@"resource":@"TurboAppSDKWeather",@"name":@"天气 · 图标示例",@"detail":@"3 页 · 天气图标 / 预报 / 指数 · 非实时数据"},
 @{@"resource":@"TurboAppSDKMusic",@"name":@"音乐播放器 · 演示",@"detail":@"4 页 · 封面 / 歌词 / 暂停态 · 不播放音频"},
 @{@"resource":@"TurboAppSDKDevice",@"name":@"设备状态 · 示例",@"detail":@"2 页 · 自定义图标 / 容量 / 额度 · 固定数据"}];}
static NSDictionary *BuiltinPackage(NSUInteger index,NSString **error){if(index>=Builtins().count)return nil;NSString *path=[NSBundle.mainBundle pathForResource:Builtins()[index][@"resource"] ofType:@"zip"];return TAPReadPackage(path?[NSData dataWithContentsOfFile:path]:nil,error);}
@interface TAPPreview:UIView
@property(nonatomic,strong) NSDictionary *document;
@property(nonatomic) NSUInteger page;
@end
@implementation TAPPreview
- (void)setDocument:(NSDictionary *)d{_document=d;[self setNeedsDisplay];}
- (void)setPage:(NSUInteger)p{_page=p;[self setNeedsDisplay];}
- (void)drawRect:(CGRect)rect{
 CGContextRef ctx=UIGraphicsGetCurrentContext();[UIColor.blackColor setFill];UIRectFill(self.bounds);NSArray *pages=_document[@"pages"];if(_page>=pages.count)return;
 CGContextSaveGState(ctx);CGFloat scale=self.bounds.size.width/540;CGContextScaleCTM(ctx,scale,scale);UIColor *green=[UIColor colorWithRed:.17 green:1 blue:.25 alpha:1];BOOL focused=NO;
 for(NSDictionary *c in pages[_page][@"components"]){CGRect r=CGRectMake([c[@"x"]doubleValue],[c[@"y"]doubleValue],[c[@"w"]doubleValue],[c[@"h"]doubleValue]);NSString *kind=c[@"kind"];CGContextSaveGState(ctx);CGContextClipToRect(ctx,r);
  if([kind isEqual:@"text"]||[kind isEqual:@"button"]){if([kind isEqual:@"button"]){[green setStroke];UIBezierPath *p=[UIBezierPath bezierPathWithRect:CGRectInset(r,.5,.5)];p.lineWidth=focused?1:2;[p stroke];focused=YES;}
   NSMutableParagraphStyle *style=[NSMutableParagraphStyle new];style.lineBreakMode=NSLineBreakByClipping;[c[@"text"]drawInRect:r withAttributes:@{NSFontAttributeName:[UIFont systemFontOfSize:[c[@"font"]doubleValue]],NSForegroundColorAttributeName:green,NSParagraphStyleAttributeName:style}];
  }else if([kind isEqual:@"frame"]){[green setStroke];[[UIBezierPath bezierPathWithRect:CGRectInset(r,.5,.5)]stroke];}
  else if([kind isEqual:@"progress"]){[[green colorWithAlphaComponent:.2]setFill];UIRectFill(r);r.size.width*=[c[@"value"]doubleValue]/100;[green setFill];UIRectFill(r);}
  else if([kind isEqual:@"image"]){NSDictionary *a=_document[@"assets"][c[@"asset"]];NSData *data=[[NSData alloc]initWithBase64EncodedString:a[@"pixels"] options:0];const uint8_t *b=data.bytes;unsigned w=[a[@"width"]unsignedIntValue],h=[a[@"height"]unsignedIntValue];if(w&&data.length==w*h/8){[green setFill];for(unsigned y=0;y<h;y++)for(unsigned x=0;x<w;x++)if(b[y*(w/8)+x/8]&(128>>(x%8)))UIRectFill(CGRectMake(r.origin.x+x,r.origin.y+y,1,1));}}
  CGContextRestoreGState(ctx);
 }CGContextRestoreGState(ctx);
}
@end
@interface TAPReview:UIViewController
@property NSDictionary *package;
@property TAPPreview *preview;
@property UILabel *status;
@property UIButton *install;
@end
@implementation TAPReview
- (void)viewDidLoad{[super viewDidLoad];self.title=_package[@"document"][@"name"];self.view.backgroundColor=TIOPaper();self.overrideUserInterfaceStyle=UIUserInterfaceStyleDark;
 UINavigationBarAppearance *appearance=[UINavigationBarAppearance new];[appearance configureWithDefaultBackground];appearance.backgroundColor=TIOPaper();appearance.titleTextAttributes=@{NSForegroundColorAttributeName:TIOInk()};self.navigationItem.standardAppearance=appearance;self.navigationItem.scrollEdgeAppearance=appearance;
 _preview=[TAPPreview new];_preview.document=_package[@"document"];_preview.layer.cornerRadius=12;_preview.clipsToBounds=YES;[_preview.heightAnchor constraintEqualToAnchor:_preview.widthAnchor multiplier:180.0/540].active=YES;
 NSMutableArray *names=[NSMutableArray new];for(NSDictionary *p in _package[@"document"][@"pages"])[names addObject:p[@"id"]];UISegmentedControl *pages=[[UISegmentedControl alloc]initWithItems:names];pages.selectedSegmentIndex=0;[pages addTarget:self action:@selector(page:) forControlEvents:UIControlEventValueChanged];
 UILabel *info=[UILabel new];info.numberOfLines=0;info.font=[UIFont systemFontOfSize:14];info.textColor=TIOInk();info.text=[NSString stringWithFormat:@"%@ · v%@\n%lu 页 · %@ 字节（解压）\n540 × 180 原生组件预览，字体以镜片为准。\n权限：%@\nZIP SHA-256\n%@",_package[@"document"][@"id"],_package[@"document"][@"version"],(unsigned long)names.count,_package[@"unpackedBytes"],[_package[@"document"][@"permissions"]count]?@"后端按钮事件（此版尚不外发）":@"无网络、麦克风或定位权限",_package[@"zipSHA256"]];
 UIButton *query=[UIButton buttonWithType:UIButtonTypeSystem];[query setTitle:@"查询眼镜当前槽位" forState:UIControlStateNormal];[query addTarget:self action:@selector(query) forControlEvents:UIControlEventTouchUpInside];TIOStyleAction(query,NO,NO);[query.heightAnchor constraintEqualToConstant:48].active=YES;
 _install=[UIButton buttonWithType:UIButtonTypeSystem];[_install setTitle:@"确认安装这个应用" forState:UIControlStateNormal];[_install addTarget:self action:@selector(confirm) forControlEvents:UIControlEventTouchUpInside];TIOStyleAction(_install,YES,NO);[_install.heightAnchor constraintEqualToConstant:50].active=YES;
 _status=[UILabel new];_status.numberOfLines=0;_status.font=[UIFont systemFontOfSize:14];_status.textColor=TIOInk();
 UIScrollView *scroll=[UIScrollView new];scroll.translatesAutoresizingMaskIntoConstraints=NO;[self.view addSubview:scroll];[NSLayoutConstraint activateConstraints:@[[scroll.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor],[scroll.bottomAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.bottomAnchor],[scroll.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor],[scroll.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor]]];UIStackView *stack=[[UIStackView alloc]initWithArrangedSubviews:@[_preview,pages,info,query,_install,_status]];stack.axis=UILayoutConstraintAxisVertical;stack.spacing=18;stack.translatesAutoresizingMaskIntoConstraints=NO;[scroll addSubview:stack];[NSLayoutConstraint activateConstraints:@[[stack.topAnchor constraintEqualToAnchor:scroll.contentLayoutGuide.topAnchor constant:20],[stack.bottomAnchor constraintEqualToAnchor:scroll.contentLayoutGuide.bottomAnchor constant:-24],[stack.leadingAnchor constraintEqualToAnchor:scroll.frameLayoutGuide.leadingAnchor constant:20],[stack.trailingAnchor constraintEqualToAnchor:scroll.frameLayoutGuide.trailingAnchor constant:-20]]];[NSNotificationCenter.defaultCenter addObserver:self selector:@selector(refresh) name:@"TAPPhoneChanged" object:nil];[self refresh];}
- (void)dealloc{[NSNotificationCenter.defaultCenter removeObserver:self];}
- (void)refresh{_status.text=TAPPhoneBridge.shared.note;_install.enabled=TAPPhoneBridge.shared.ready;}
- (void)page:(UISegmentedControl *)s{_preview.page=s.selectedSegmentIndex;}
- (void)query{[TAPPhoneBridge.shared query];}
- (void)confirm{TAPPhoneBridge *b=TAPPhoneBridge.shared;if(!b.ready){Notice(self,@"先查询当前眼镜的槽位状态。");return;}NSString *peer=[b.peer copy];NSDictionary *snapshot=b.snapshot,*package=_package;UIAlertController *a=[UIAlertController alertControllerWithTitle:@"安装到当前眼镜？" message:@"只安装此预览包，不刷固件。最多四个应用；相同 ID 仅允许更高版本更新。请让眼镜回首页并结束其他任务。" preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"确认安装" style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){if(!b.ready||![b.peer isEqual:peer]||![b.snapshot isEqual:snapshot]){Notice(self,@"会话状态已变化，请重新查询和确认。");return;}[b install:package];}]];[self presentViewController:a animated:YES completion:nil];}
@end
#include "AppGallery.inc"
@interface TAPLibrary:UITableViewController<UIDocumentPickerDelegate>
@property BOOL importing;
@property NSInteger mode;
@property UISegmentedControl *tabs;
@end
@implementation TAPLibrary
- (void)viewDidLayoutSubviews{[super viewDidLayoutSubviews];UIView *h=self.tableView.tableHeaderView;CGFloat w=self.tableView.bounds.size.width;h.frame=CGRectMake(0,0,w,176);NSArray<UIView *> *v=h.subviews;if(v.count>=3){v[0].frame=CGRectMake(20,12,w-40,36);v[1].frame=CGRectMake(20,54,w-40,48);_tabs.frame=CGRectMake(20,120,w-40,38);}}
- (void)viewDidLoad{[super viewDidLoad];self.title=@"应用广场";self.mode=1;TIOStyleResearchTable(self);UIView *h=[[UIView alloc]initWithFrame:CGRectMake(0,0,360,176)];UILabel *title=[[UILabel alloc]initWithFrame:CGRectMake(20,12,320,36)];title.autoresizingMask=UIViewAutoresizingFlexibleWidth;title.text=@"把想法，戴在眼前。";title.font=[UIFont systemFontOfSize:25 weight:UIFontWeightSemibold];title.textColor=TIOInk();[h addSubview:title];UILabel *detail=[[UILabel alloc]initWithFrame:CGRectMake(20,54,320,48)];detail.autoresizingMask=UIViewAutoresizingFlexibleWidth;detail.text=@"20 个 MCP 灵感模板\n连接你自己的 Server，创造自己的小应用。";detail.numberOfLines=2;detail.textColor=UIColor.secondaryLabelColor;detail.font=[UIFont systemFontOfSize:14];[h addSubview:detail];_tabs=[[UISegmentedControl alloc]initWithItems:@[@"我的应用",@"应用广场",@"开发指南"]];_tabs.frame=CGRectMake(20,120,320,38);_tabs.autoresizingMask=UIViewAutoresizingFlexibleWidth;_tabs.selectedSegmentIndex=1;_tabs.selectedSegmentTintColor=[TIOAccent()colorWithAlphaComponent:.20];[_tabs addTarget:self action:@selector(switchTab:) forControlEvents:UIControlEventValueChanged];_tabs.accessibilityIdentifier=@"apps-sections";[h addSubview:_tabs];self.tableView.tableHeaderView=h;[NSNotificationCenter.defaultCenter addObserver:self selector:@selector(refresh) name:@"TAPPhoneChanged" object:nil];}
- (void)querySlotsOnEntry{if(_mode==0&&!_importing&&!TAPPhoneBridge.shared.busy)[TAPPhoneBridge.shared query];}
- (void)switchTab:(UISegmentedControl *)tabs{self.mode=tabs.selectedSegmentIndex;[self refresh];[self.tableView setContentOffset:CGPointMake(0,-self.tableView.adjustedContentInset.top) animated:NO];[self querySlotsOnEntry];}
- (void)dealloc{[NSNotificationCenter.defaultCenter removeObserver:self];}
- (void)viewWillAppear:(BOOL)a{[super viewWillAppear:a];UILabel *label=[UILabel new];label.text=self.title;label.textColor=TIOInk();label.font=[UIFont systemFontOfSize:17 weight:UIFontWeightSemibold];[label sizeToFit];self.navigationItem.titleView=label;[self refresh];}
- (void)viewDidAppear:(BOOL)a{[super viewDidAppear:a];[self querySlotsOnEntry];}
- (void)refresh{[self.tableView reloadData];}
- (NSInteger)numberOfSectionsInTableView:(UITableView *)table{return _mode==2?1:2;}
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s{return _mode==2?4:_mode==1?(s?GalleryItems().count:Builtins().count):(s?4:2);}
- (CGFloat)tableView:(UITableView *)t heightForRowAtIndexPath:(NSIndexPath *)p{return _mode==1?112:UITableViewAutomaticDimension;}
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s{return _mode==2?@"从零到一个原生小应用":_mode==1?(s?@"MCP 灵感模板 · 连接自己的 Server":@"精选 · 先试一试"):(s?@"眼镜应用槽位 · 最多四个":@"安装与管理");}
- (NSString *)tableView:(UITableView *)t titleForFooterInSection:(NSInteger)s{return _mode==2?@"MCP、数据获取与凭据都在你自己的 Server。手机预览并确认安装，眼镜只运行有界原生界面。":_mode==1?(s?@"以上是可安装的离线模板，不代表对应在线服务已连接；详情内可复制开发提示词。":@"示例均为固定数据，音乐示例不播放音频。"):(s?@"旋钮滚动选择，短按执行，长按退出。最多四个应用，只运行一个。":TAPPhoneBridge.shared.note);}
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)p{UITableViewCell *c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil];TIOStyleResearchCell(c);c.detailTextLabel.numberOfLines=2;TAPPhoneBridge *b=TAPPhoneBridge.shared;
 if(_mode==2){c.textLabel.text=@[@"复制完整开发任务",@"复制 Skill 安装命令",@"仪表盘与 App SDK 文档",@"Server 与发布边界"][p.row];c.detailTextLabel.text=@[@"交给 Agent：开发、打包、校验、导入",@"由你确认后安装到自己的 Agent",@"API、Schema、ZIP、测试与 GitHub 分发",@"查看快照更新、权限和已知限制"][p.row];c.imageView.image=[UIImage systemImageNamed:@[@"doc.on.doc",@"terminal",@"book.closed",@"server.rack"][p.row]];c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;return c;}
 if(_mode==1){NSDictionary *item=p.section?GalleryItems()[p.row]:Builtins()[p.row];c.textLabel.text=item[@"name"];c.detailTextLabel.text=p.section?[NSString stringWithFormat:@"%@ · 离线模板\n%@",item[@"category"],item[@"purpose"]]:item[@"detail"];c.detailTextLabel.numberOfLines=3;c.accessibilityIdentifier=[(p.section?@"recipe-":@"builtin-")stringByAppendingString:p.section?item[@"id"]:item[@"resource"]];if(p.section){c.imageView.image=[UIImage systemImageNamed:item[@"symbol"]]?:[UIImage systemImageNamed:@"app"] ;c.imageView.tintColor=TIOAccent();c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;}else{NSDictionary *pkg=BuiltinPackage(p.row,nil);TAPPreview *preview=[[TAPPreview alloc]initWithFrame:CGRectMake(0,0,108,36)];preview.document=pkg[@"document"];preview.layer.cornerRadius=5;preview.clipsToBounds=YES;c.accessoryView=preview;}return c;}
 if(!p.section){c.textLabel.text=p.row?(_importing?@"正在校验…":@"导入应用 ZIP"):(b.busy?@"正在等待眼镜…":@"查询四槽状态");c.detailTextLabel.text=p.row?@"预览每页、核对权限与 SHA-256 后安装":@"只读查询，不启动应用、不自动刷固件";c.imageView.image=[UIImage systemImageNamed:p.row?@"square.and.arrow.down":@"arrow.clockwise"];}else{id row=b.snapshot?b.snapshot[@"slots"][p.row]:nil;BOOL live=[row isKindOfClass:NSDictionary.class]&&![row[@"tombstone"]boolValue];c.textLabel.text=live?row[@"name"]:[NSString stringWithFormat:@"槽位 %ld · %@",(long)p.row+1,b.snapshot?@"空闲":@"未读取"];c.detailTextLabel.text=live?[NSString stringWithFormat:@"%@ · v%@%@",row[@"id"],row[@"version"],[b.snapshot[@"activeSlot"]integerValue]==p.row?@" · 正在运行":@""]:@"从手机导入，眼镜“我的应用”中打开";c.imageView.image=[UIImage systemImageNamed:live?@"app.dashed":@"plus.app"];c.accessoryType=live?UITableViewCellAccessoryDisclosureIndicator:UITableViewCellAccessoryNone;}return c;}
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)p{[t deselectRowAtIndexPath:p animated:YES];if(_mode==2){if(p.row==0)CopyPrompt(self,DeveloperPrompt());else if(p.row==1)CopyPrompt(self,@"npx skills add Turbo1123/Turbo-IO --skill turboio-developer -g");else if(p.row==2)[UIApplication.sharedApplication openURL:[NSURL URLWithString:@"https://github.com/Turbo1123/Turbo-IO/blob/main/docs/DEVELOPER_ECOSYSTEM.md"] options:@{} completionHandler:nil];else Notice(self,@"用户 Server 连接 MCP → 白名单展示字段 → 仪表盘 API 或 App ZIP → 手机批准 → 眼镜。App v1 为手动安装的数据快照；自动更新和按钮事件回流尚未接通。不要把 GitHub 当作私有数据/密钥仓库。");return;}if(_mode==1){if(p.section){TAPRecipe *v=[[TAPRecipe alloc]initWithStyle:UITableViewStyleInsetGrouped];v.item=GalleryItems()[p.row];[self.navigationController pushViewController:v animated:YES];}else{NSString *error=nil;NSDictionary *package=BuiltinPackage(p.row,&error);if(!package){Notice(self,error?:@"此构建未附带示例包。");return;}TAPReview *review=[TAPReview new];review.package=package;[self.navigationController pushViewController:review animated:YES];}return;}TAPPhoneBridge *b=TAPPhoneBridge.shared;if(b.busy||_importing){Notice(self,@"当前操作尚未完成，请等待。");return;}if(!p.section){if(!p.row){[b query];return;}UIDocumentPickerViewController *picker=[[UIDocumentPickerViewController alloc]initForOpeningContentTypes:@[UTTypeZIP] asCopy:NO];picker.delegate=self;picker.allowsMultipleSelection=NO;[self presentViewController:picker animated:YES completion:nil];return;}
 id row=b.snapshot?b.snapshot[@"slots"][p.row]:nil;if(![row isKindOfClass:NSDictionary.class]||[row[@"tombstone"]boolValue])return;if(!b.ready){Notice(self,@"先重新查询眼镜槽位。");return;}NSString *peer=[b.peer copy];unsigned slot=(unsigned)p.row;UIAlertController *a=[UIAlertController alertControllerWithTitle:row[@"name"] message:@"控制当前槽位中的这一版本；不会影响其他应用。" preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]];
 for(NSNumber *n in @[@3,@4,@5]){unsigned op=n.unsignedIntValue;[a addAction:[UIAlertAction actionWithTitle:op==3?@"在眼镜打开":op==4?@"停止这个应用":@"卸载这个应用" style:op==5?UIAlertActionStyleDestructive:UIAlertActionStyleDefault handler:^(UIAlertAction *x){if(![peer isEqual:b.peer]){Notice(self,@"设备变化，未发送。");return;}[b operate:op slot:slot expected:row];}]];}[self presentViewController:a animated:YES completion:nil];}
- (void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocumentsAtURLs:(NSArray<NSURL *> *)urls{if(urls.count!=1||_importing)return;_importing=YES;[self refresh];NSURL *url=urls[0];__weak typeof(self) weak=self;dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED,0),^{BOOL scoped=[url startAccessingSecurityScopedResource];__block NSData *zip=nil;NSFileCoordinator *coordinator=[[NSFileCoordinator alloc]initWithFilePresenter:nil];[coordinator coordinateReadingItemAtURL:url options:0 error:nil byAccessor:^(NSURL *file){NSFileHandle *h=[NSFileHandle fileHandleForReadingFromURL:file error:nil];@try{zip=[h readDataUpToLength:24577 error:nil];}@finally{[h closeAndReturnError:nil];}}];if(scoped)[url stopAccessingSecurityScopedResource];NSString *error=nil;NSDictionary *package=TAPReadPackage(zip,&error);dispatch_async(dispatch_get_main_queue(),^{TAPLibrary *s=weak;if(!s)return;s.importing=NO;[s refresh];if(!s.view.window)return;if(!package){Notice(s,error?:@"读取失败。请先把文件下载到本机后重试。");return;}TAPReview *review=[TAPReview new];review.package=package;[s.navigationController pushViewController:review animated:YES];});});}
@end
UIViewController *TAPAppsController(void){return [[TAPLibrary alloc]initWithStyle:UITableViewStyleInsetGrouped];}
